### ISSUE TITLE
CKEditor field on a Assets field layout will not retain its data on save

### ISSUE THREAD

**Issue by angrybrad** [craftcms/ckeditor#10]
Steps to reproduce:

1.  Create a Volume and put some assets in it.
2.  Create a CKEditor field and put it on the Volumne's field layout.
3.  Go to Asset index page and double click an asset to edit it.
4.  Add some data in the CKEditor field and save.
5.  Edit the Asset again and notice the data didn't save.  No JavaScript errors, looks like it's just missing in POST data on save.

**Versions:**
* Craft 3.0.10.1
* CKEditor 1.0.0-beta2

**Comment by matevisky** [comment]
Thx @angrybrad Appreciate your effort

**Comment by jamiematrix** [comment]
Is there any update/progress on this? 
We're having an issue where a CKEditor field won't save it's contents (no matter what the contents are). The field is required in the entry and where the editor field empties the entry cannot save. Oddly, entries that are already in place can save (and update with new content).

Using same version of CK, but 3.3.14 and 3.3.20.1 Craft.

**Comment by brandonkelly** [comment]
This was the same root issue as #22, and just got it fixed in CKEditor 1.0.0-beta.3.
