### ISSUE TITLE
No image resize functionality

### ISSUE THREAD

**Issue by isaacwingate** [craftcms/ckeditor#101]
### Description
No image resize handles are shown in the editor and config options for resize buttons don't work. Is this feature missing intentionally ?

### Additional info

- Craft version: 4.4.9
- PHP version: 8.1

**Comment by brandonkelly** [comment]
You can choose a transform when inserting an asset. We are going to be implementing a custom image plugin that allows changing the transform afterward, but haven’t gotten around to it quite yet.

**Comment by isaacwingate** [comment]
Okay. Do you plan on adding the same [Image Resize functionality](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-resizing.html) as ckeditor5 in the future?

**Comment by brandonkelly** [comment]
That plugin only changes the image’s `width` and `height` values, but keeps the same source image dimensions. We may be able to borrow some of its dropdown UI, but ideally our solution is backed by actual image transforms.

**Comment by brandonkelly** [comment]
We just released CKEditor 3.4.0 with a new image transform dropdown within the image toolbar – see https://github.com/craftcms/ckeditor/discussions/94#discussioncomment-5920028.

**Comment by J-Protz** [comment]
Sorry to open an old thread but I need the image resize functionality, I inherited a site and they just want to be able to resize an image and see the text wrap around it. 

They could use transforms, but the previous devs already defined a good 20 transforms for general templating and the client finds this very confusing.

Is it possible to get the resize plugin working?

**Comment by justenh** [comment]
👋  We're in the same boat here. Why not enable the ImageResize plugin? Given that it looks like it's a first party plugin to CKEditor, it feels like it should be up to us/admins if we really need an image transform instead of just style width solution.
