### ISSUE TITLE
Few things

### ISSUE THREAD

**Issue by wmdhosting** [craftcms/ckeditor#103]
Hey :)

### 2. New image  transform is great, but when i add other image options in config,  transform do not show
I think all this option would be great by deafult.. 
 ` "image": {
    "toolbar": [
      "imageStyle:inline",
      "imageStyle:wrapText",
      "imageStyle:breakText",
      "|",
      "toggleImageCaption",
      "imageTextAlternative"`

### 3. Is it posiblle to add all table options by deafult. Tableproperties, Cellproperties
![Snag_5366dee0](https://github.com/craftcms/ckeditor/assets/76176291/565c78bd-dbd4-4c54-bee9-fdf3aa8daac5)
Tableproperties, Cellproperties

### 4. How to add for example Template button. .
![Snag_5368f164](https://github.com/craftcms/ckeditor/assets/76176291/531c0b1a-d6c2-421b-9832-926ab6179403)

Thx

### Additional info

- Craft version: Craft Pro 4.4.11

- Plugins & versions: CKEditor | 3.4.0

**Comment by brandonkelly** [comment]
Thanks for posting! Unfortunately it’s hard for us to take action on issues that cover multiple things, so can you please post these as individual [Q&A discussions](https://github.com/craftcms/ckeditor/discussions/new?category=q-a) / [Idea discussions](https://github.com/craftcms/ckeditor/discussions/new?category=ideas) depending on their nature? (_Issues_ should only be used for actual bug reports – which none of these points are.)

**Comment by brandonkelly** [comment]
> 1. Dont see how is posiblle for links to **Open in new window**

Add the following to your Config Options:

```json
{
  "link": {
    "decorators": {
      "isExternal": {
        "attributes": {
          "rel": "noopener noreferrer",
          "target": "_blank"
        },
        "label": "Open in a new tab",
        "mode": "manual"
      }
    }
  }
}
```

> 2. New image transform is great, but when i add other image options in config, transform do not show

You can choose which image transforms should be available to the editor from the field settings, under the **Assets** section.

<img src="https://github.com/craftcms/ckeditor/assets/47792/2f42bb78-0e18-4843-b11a-189a53e7347e" width="482" height="334" alt="the Assets section of a CKEditor’s field settings">

> 3. Is it posiblle to add all table options by deafult. Tableproperties, Cellproperties

I’ve just included TableProperties and TableCellProperties in the core build (3426ecd5dcce63895e2289e810377900b60f4c8c). You will still need to configure them manually, though:

```json
{
  "table": {
    "contentToolbar": [
      "tableRow",
      "tableColumn",
      "mergeTableCells",
      "|",
      "tableProperties",
      "tableCellProperties"
    ],
    "tableCellProperties": {
      "backgroundColors": [
        {
          "color": "hsl(120, 75%, 60%)",
          "label": "Green"
        }
      ]
    }
  }
}
```

> How to add for example Template button. .

Templates is a premium CKEditor plugin, which requires an enterprise license to access, which we don’t currently have.



---

In the future, please post these as individual [Q&A discussions](https://github.com/craftcms/ckeditor/discussions/new?category=q-a) / [Idea discussions](https://github.com/craftcms/ckeditor/discussions/new?category=ideas) depending on their nature. (_Issues_ should only be used for actual bug reports – which none of these points are.)
