### ISSUE TITLE
Request: Keyboard shortcuts for headings

### ISSUE THREAD

**Issue by darylknight** [craftcms/ckeditor#106]
In Redactor, you can use keyboard shortcuts on Mac and Windows to transform selected text into heading styles using `ctrl+alt+[1-6]`. Any chance of adding that functionality to the CK Editor plugin?

**Comment by i-just** [comment]
Hi, thanks for getting in touch. 

We’ll discuss the keyboard shortcuts internally. 

For now, here are the shortcuts supported by CKEditor: https://ckeditor.com/docs/ckeditor5/latest/features/keyboard-support.html, and you can use Markdown to change a line of text into a heading quickly. 

From the CKEditor documentation: “_Headings – Start a line with # or ## or ### followed by a space to create a heading 1, heading 2, or heading 3 (up to heading 6 if options defines more headings)”_. More info can be found here: https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html.

**Comment by brandonkelly** [comment]
CKEditor 3.5.0 is out with support for Redactor-style keyboard shortcuts :tada: (#116)

Note that the update requires [Craft 4.5.0](https://craftcms.com/blog/craft-4-5-released).
