### ISSUE TITLE
FR: character/word limit option

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/ckeditor#107]
### Description
It would be great if we could have a character (or word) limit option just like Redactor has (but preferably better with copy/paste support).

I cannot find anything in the CKEditor docs about this except some examples with word count which is unfortunately not the same as it is not a hard limitation.

**Comment by brandonkelly** [comment]
Added for the next release!

**Comment by brandonkelly** [comment]
CKEditor 3.5.0 is out with the new Word Limit setting :tada:

Note that the update requires [Craft 4.5.0](https://craftcms.com/blog/craft-4-5-released).

**Comment by Lugo778** [comment]
Lo mejor de la vida si sabes usarlo

**Comment by samuelreichor** [comment]
@brandonkelly I find word limitations kind of tricky because words can be very long. A character limit would be cooler. I will never be able to use Word Limitations like this. Is there any chance that this will be changed to a character limit? #pneumonoultramicroscopicsilicovolcanoconiosis :D

**Comment by terryupton** [comment]
Any update on setting up character limits?

**Comment by elivz** [comment]
We were also hoping for a character count option, similar to Redactor. Before I dive into customizing the plugin, I don't suppose that option is planned for the near future?

**Comment by CrystalHolmes** [comment]
A character count option would be fantastic so we can best maintain the integrity of our design.

**Comment by i-just** [comment]
Hi All,

The first-party `WordCount` plugin is already included in Craft’s CKEditor plugin. It can show word and/or character counts and include logic on what should happen as you type (e.g. when you get near or over the limit).
If you toggle “Show word count” in the CKEditor field’s setting, you get the word count shown underneath the field. To turn on character count, go to CKEditor Config used by that field and add the following under “Config Options”:
```
"wordCount": {
    "displayCharacters": true,
    "displayWords": true
}
```

That configuration can then be further customised to meet your needs. More info on that here: https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html.

We’ll discuss character limits internally.

**Comment by elivz** [comment]
Amazing, thank you!

**Comment by brandonkelly** [comment]
CKEditor 3.13.0 and 4.8.0 are out, replacing the Word Limit setting with “Field Limit”, which can be set to either words or characters. (#384)
