### ISSUE TITLE
'Insert link' is not translated

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/ckeditor#111]
### Description

The button label _Insert link_ in the link dropdown is not translated (checked in German, Dutch, French). Looks like it's not marked as translatable, or it's missing a translation in all those languages.

![Screenshot 2023-06-20 at 14 02 07](https://github.com/craftcms/ckeditor/assets/10146880/1dad8cc7-f8c6-47cf-8b8f-1c1924a16c0c)

Not sure where those translations come from, is this an issue with the plugin or with CKEditor itself?

### Additional info

- Craft version: 4.4.13
- PHP version: 8.2
- Plugins & versions: 
    - CKEditor 3.4.0

**Comment by eddiedale** [comment]
I don't believe this is a bug, but just a missing translation. It works to create a translations/de/ckeditor.php with the specific translation as a workaround, but optimally add the updated translations as a pull request :-)

**Comment by MoritzLost** [comment]
@eddiedale Thanks! I didn't know CKEditor used a custom translation category, good to know.

Still not sure I have the full picture – looks like CKEditor comes with its own translations as far as I can tell, because there are some strings that are translated to German but don't appear in the [translations file](https://github.com/craftcms/ckeditor/blob/main/src/translations/de/ckeditor.php). There're a lot of translations missing [compared to `en`](https://github.com/craftcms/ckeditor/blob/main/src/translations/en/ckeditor.php), those should probably be added in the plugin itself? Or even in CKEditors translations?

**Comment by brandonkelly** [comment]
Thanks @MoritzLost!
