### ISSUE TITLE
Edit toolbar? Source mode?

### ISSUE THREAD

**Issue by heymarkreeves** [craftcms/ckeditor#12]
[Is it|Will it be] possible to custom the options available in the toolbar? [Is there|Will there be] a source mode option to edit HTML directly? Thanks!

**Comment by onurozkan** [comment]
@circa1977 

https://github.com/ckeditor/ckeditor5/issues/592#issuecomment-335108129

**Comment by sokolovstas** [comment]
#19  allow edit toolbar

**Comment by brandonkelly** [comment]
We just released version 1.0.0 of the plugin, which now [allows full control](https://github.com/craftcms/ckeditor#editor-configuration) over the editor configuration.
