### ISSUE TITLE
Field padding missing when opening entry slideouts multiple times

### ISSUE THREAD

**Issue by thupsi** [craftcms/ckeditor#126]
### Description
The internal padding of the text in a CKEditor field is missing when the user opens an entry via slideout, closes the slideout and then opens the same entry or another one.

### Steps to reproduce

1. Go to the entry index
2. Open an entry slideout with a CKEditor field in it. Notice that the field padding is normal
3. Close the slideout
4. Open a new slideout
5. Notice that the padding is missing

### Additional info

- Craft version: 4.5
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting! Just released CKEditor 3.5.1 with a fix for this.
