### ISSUE TITLE
Links cause errors in slideouts

### ISSUE THREAD

**Issue by thupsi** [craftcms/ckeditor#128]
### Description

The following bugs appear when a CKEditor field contains a link and the entry is opened in a slideout **without changing anything**:

1. If the user clicks outside the slideout there is a browser warning `Are you sure you want to close this screen? Any changes will be lost.`
2. If the user clicks the `Open the full edit page in a new tab` button on the top right an autosave takes place and the field gets marked as dirty. The button works as expected only on a consecutive click.

### Steps to reproduce

1. Open a slideout of an entry with a CKEditor field containing a link
2. Without editing the entry, click outside the slideout OR click the `Open the full edit page in a new tab` button on the top right.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions: CKEDitor 3.5.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! This will be fixed by Craft 4.5.3.

**Comment by brandonkelly** [comment]
Craft 4.5.3 is out now with a fix for this.
