### ISSUE TITLE
Config Options and Custom Styles mixed up

### ISSUE THREAD

**Issue by idleog** [craftcms/ckeditor#129]
### Description
Config setting shows same content for 'Config options' and 'Custom Styles'. The values have been setup by './craft project-config/apply', deployed on live server from local machine.

Changing one or another field, (or deleting them) changes both fields. (see screenshots)

It's weird this is only on my production environment, not on the corresponding local one. 

### What I did

1. Installed CKEditor plugin on local machine
2. Generated one CKEditor field (and corepsonding config setting)
3. Converted existing Redactor fields with 'craft ckeditor/convert' (worked like a charm)
4. installed CKEditor plugin on production
5. deployed Config files to production server
6. run 'craft project-config/apply' on production

The project config files for the CKEditor config settings show the correct values for css and options. As well, the css custom styles are correct in the CKEditor fields. It seems that the problem is only on the CKEditor Config Mask

### Additional info

- Craft version: 4.5.2
- PHP version: 8.2.8
- Database driver & version: MariaDB 10.6.14
- Plugins & versions: CKEditor  3.5.0 //  Cloner  2.0.3 //  Control Panel CSS  2.6.0 //  Cookies  4.0.0 //  Enupal Snapshot  2.0.2 //  Incognito Field  1.3.0 //  Redactor  3.0.4 //  Site Switcher  2.3.0 //  Typed link field  2.1.5 //  Wordsmith  4.2.0

<img width="817" alt="Bildschirmfoto 2023-08-25 um 11 52 27" src="https://github.com/craftcms/ckeditor/assets/870071/9c655ff9-a2ac-4fa9-be5e-81744e53fdd8">
<img width="731" alt="Bildschirmfoto 2023-08-25 um 11 52 06" src="https://github.com/craftcms/ckeditor/assets/870071/9e93807c-1faf-4153-8837-7a42e823d6ab">

[project.zip](https://github.com/craftcms/ckeditor/files/12438008/project.zip)

**Comment by brandonkelly** [comment]
Very strange. I’m not able to reproduce this.

Can you try running the following command on production?

```sh
php craft project-config/apply --force
```

**Comment by idleog** [comment]
I tried with the --force option, did not help...
At least all things are correct on production site, when I do the changes on dev environment and deploy to production.

**Comment by brandonkelly** [comment]
So you’re saving that the fields are still working correctly; it’s just that the CKEditor Config settings are showing the incorrect values?

**Comment by idleog** [comment]
Correct. Any settings I set on local machine, upload (via config project files) and apply on production, are behaving correctly. But shown wrong on production ckeditor config masks. And are not editable there.

**Comment by brandonkelly** [comment]
Would you be able to share your production database backup and Composer files, so we can try to reproduce with them? If so you can send them to support@craftcms.com.

**Comment by idleog** [comment]
Your comment inspired me to run `composer update` on production... and it solved the problem! (maybe sth with nystudio107/craft-code-editor (which was updated to 1.0.13)?
Thanks anyway for your help!

**Comment by brandonkelly** [comment]
Oh great! Thanks for the update, and glad it’s sorted now.

**Comment by idleog** [comment]
Thank you for your help and your great work. I really like the CKEditor plugin!
