### ISSUE TITLE
Customize the toolbar

### ISSUE THREAD

**Issue by CreateSean** [craftcms/ckeditor#13]
My client is requesting optoins in the toolbar that are not there including:

change text alignment

when editing links shoudl be able to set the target i.e. target="_blank"

I can't find this in the documentation. If it's not available now, how soon? also would we lose any data by switching from ckeditor to redactor if we needed to?

**Comment by nevsie** [comment]
I am also interested. 
Seems like they are not too fussed!

But if you wish, you can download your own build of CKE5
https://ckeditor.com/ckeditor-5/download/

And then backup the original and replace, giving you the options in your build... But...
I cannot say if this is safe or usable... but it does show the new editor.

look in:
vendor/craftcms/ckeditor/lib/ckeditor/dist/

Will most likely be replaced when updating, if ever is...
N

**Comment by tobiasmillauer** [comment]
+1

**Comment by brandonkelly** [comment]
We just released version 1.0.0 of the plugin, which now [allows full control](https://github.com/craftcms/ckeditor#editor-configuration) over the editor configuration.
