### ISSUE TITLE
Built-In Plugin "Text-Part-Language" - translations could not be overridden

### ISSUE THREAD

**Issue by alexkuzmin** [craftcms/ckeditor#130]
### Translations for built-in plugins "Text-Part-Language" does not work

<img width="1120" alt="Screenshot 2023-08-28 at 13 55 27" src="https://github.com/craftcms/ckeditor/assets/3720262/09503faa-d3df-458c-a99a-f3ef22f38196">

I'm trying to override the translations for "Text-Part-Language", which is built-in in Craft-CKEditor. The translations are placed in /translations/de/ckeditor.php. Translations e.g. for Image Plugin work successfully from there, but for Text-Part-Language not. Maybe someone has a hint, how could be added the translations for that plugin? Thanks.

### Additional info

- Craft version: 4.5.0
- PHP version: 8.1.18
- Database driver & version: PostgreSQL 13.10
- Plugins & versions: CKEditor 3.5.0

**Comment by brandonkelly** [comment]
Translations provided by CKEditor packages are JS-only. All core packages’ translations get compiled into [src/web/assets/ckeditor/dist/translations](https://github.com/craftcms/ckeditor/tree/main/src/web/assets/ckeditor/dist/translations).

If it’s possible to override them (I’m not really sure), it would need to be via another [CKEditor JS plugin](https://github.com/craftcms/ckeditor#adding-ckeditor-plugins).

**Comment by alexkuzmin** [comment]
Thanks. If I add this plugin additionally as [CKEditor JS plugin](https://github.com/craftcms/ckeditor#adding-ckeditor-plugins), the translation overrides really works. At the beginning it throws an error that two plugins have the same names, so the names should be different:

```
public array $pluginNames = [
        'TextPartLanguage2', // should be different
];

public array $toolbarItems = [
        'textPartLanguage', // should be same
];
```

Then I've corrected the translations in assetbundles/[plugin]/build/translations/de.js, and they are displayed correctly.

<img width="559" alt="Screenshot 2023-08-30 at 10 36 10" src="https://github.com/craftcms/ckeditor/assets/3720262/04fd0714-ed4d-4951-9cee-9013fd6f4417">
