### ISSUE TITLE
When you have only one defined transform it doesnt show in CKEditor

### ISSUE THREAD

**Issue by FoxtrotCZ** [craftcms/ckeditor#131]
### Description
It took me quite a while to find out why I dont see transform option when clicking on inserted image in CKEditor.
Yes, often people have many transforms, but in cases when someone only begins to use Craft and have only one transform it looks like CKEditor doesnt work because of that.

### Steps to reproduce

1. Have only 1 defined transform in Assets - Image Transforms
2. Insert image in CKEditor and click on it

### Additional info

- Craft version: 4.5.2
- CKEditor: 3.5.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released CKEditor 3.5.1 with a fix.
