### ISSUE TITLE
Custom entry sources

### ISSUE THREAD

**Issue by soerenmeier** [craftcms/ckeditor#139]
### Description
Custom entry sources are not listed in the `link to an entry` menu.

### Steps to reproduce

1. Create a custom entry source and a ckeditor field.
2. click "link to an entry".

### Additional info

- Craft version: Craft Pro 4.5.6.1
- PHP version: 8.2.0
- Database driver & version: MySQL 5.7.39
- Plugins & versions:
CKEditor 3.6.0
Formie 2.0.37
SEOmatic 4.0.31

**Comment by brionwolf** [comment]
Noticing the same issue. Would be fantastic if we could also specifically select/limit _which_ sources are available similar to setting up an entries field.

### Additional info

- Craft version: Craft Pro 4.5.6.1
- PHP version: 8.2.10 
- Database driver & version: MariaDB 10.11.5
- Plugins & versions:
    - CKEditor 3.6.0
