### ISSUE TITLE
Editor doesn't load on entry versions

### ISSUE THREAD

**Issue by jmoont** [craftcms/ckeditor#14]
Steps to reproduce:

1. Create/edit current entry e.g. `/admin/entries/contentPages/slug-name/`
2. Editor loads as expected.
3. Switch to edit a previous version e.g. `/admin/entries/contentPages/slug-name/versions/163`
4. Editor doesn't load and just the textarea is visable.

Versions:
- Craft CMS 3.0.16.1 
- CKEditor 1.0.0-beta.2

**Comment by brandonkelly** [comment]
This is expected behavior. Past versions are not meant to be editable.
