### ISSUE TITLE
Update to CKEditor v40 for the multiBlock option

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/ckeditor#141]
### Description

We need the `multiBlock` option to limit author's ability to enter multiple blocks / paragraphs in a list. This is supported in CKEditor 40:

- https://github.com/ckeditor/ckeditor5/releases/tag/v40.0.0
- https://github.com/ckeditor/ckeditor5/issues/14634

However, the plugin is currently on CKEditor 39.0.2, so we can't use that option.

Bumping the CKEditor version would be greatly appreciated – thanks!

### Additional info

- Craft version: 4.5.6.1
- PHP version: 8.2
- Plugins & versions: CKEditor 3.6.0

**Comment by leevigraham** [comment]
This would also cleanup the choice between list types:

![image](https://github.com/craftcms/ckeditor/assets/25124/8cf2b344-f3e0-4450-bf7e-d23f070ac97f)

**Comment by i-just** [comment]
Hi both! Thanks for the nudge. I raised a PR to update to the latest CKEditor, switch to `TodoDocumentList` plugin and remove the no longer needed lists v1.

**Comment by MoritzLost** [comment]
༼ つ ◕_◕ ༽つ Summoning @brandonkelly for review :)

**Comment by brandonkelly** [comment]
CKEditor 3.7.0 was just released, with CKE 5 41.0.0, plus `TodoDocumentList` has been pulled in, and `List`, `ListProperties`, and `TodoList` have been removed.

**Comment by MoritzLost** [comment]
@brandonkelly @i-just Thanks! 🚀 

Is it normal that the `linkPlugin` key remains in the config object with an empty string value in `config/ckeditor` after saving the CKEditor configs?

![Screenshot 2024-02-05 at 15 28 37](https://github.com/craftcms/ckeditor/assets/10146880/cd68f76f-138b-44e0-9d92-2b232cbe06c8)

**Comment by brandonkelly** [comment]
That was overlooked, but I’ve fixed it for the next release (cd196c3a64286c04ea47c91cb169b934c38ba62a).
