### ISSUE TITLE
Remove format from block styling

### ISSUE THREAD

**Issue by Metis77** [craftcms/ckeditor#143]
### Description

https://ckeditor.com/docs/ckeditor5/latest/features/remove-format.html
The remove format feature lets you quickly remove any text formatting applied using inline HTML elements and CSS style.
This is especially needed whenever you set any block stylers.

Therefore I suggest that you bundle your ckeditor with the remove format plugin.

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 
That sounds like a good idea to me. I raised a PR to add it.

**Comment by brandonkelly** [comment]
CKEditor 3.7.0 has been released, which now bundles the `RemoveFormat` CKE plugin.
