### ISSUE TITLE
CraftCMS 5[alpha] - Query selector error for nested entry type

### ISSUE THREAD

**Issue by magnessjo** [craftcms/ckeditor#153]
### Description

Query selector error thrown with CKEditor field nested in an entry type. 

<img width="631" alt="Screenshot 2023-12-17 at 2 17 03 PM" src="https://github.com/craftcms/ckeditor/assets/856595/c3ee8a4e-875d-4680-a416-104daca47cc0">

### Steps to reproduce

1. Create a simple CKEditor field 
2. Create an entry type with CKEditor field 
3. Add entry type to a section
4. Add entry to section

### Additional info

- Craft version: Craft Pro 5.0.0-alpha.2
- PHP version: 8.2.10
- Database driver & version: MySQL 8.1.0
- Plugins & versions: CKEditor 4.0.x-dev

**Comment by brandonkelly** [comment]
This was fixed in Craft 5.0.0-alpha.3. Thanks for reporting!
