### ISSUE TITLE
Migration script missed a field named "disclaimer" on two separate sites inside a Matrix block

### ISSUE THREAD

**Issue by darylknight** [craftcms/ckeditor#155]
### Description
I just replaced Redactor with CKEditor on two similar websites, although they do not share a codebase. In both cases, a Redactor field named "Disclaimer" inside two different matrix blocks were not converted to CKEditor. I ran the migrations, then uninstalled Redactor. Migration log from one site:

![image](https://github.com/craftcms/ckeditor/assets/1250017/e187e97b-e971-4e2e-a645-e9215b1013cd)

Then found that on both websites, everything had converted correctly except these fields:

![image](https://github.com/craftcms/ckeditor/assets/1250017/cd523325-3b6e-41f5-844f-a09651c8b301)

![image](https://github.com/craftcms/ckeditor/assets/1250017/745796b9-d1e3-448b-9636-978b3fc7e90e)

### Steps to reproduce

Unknown whether the field handle is a coincidence. There were no conversion logs that noted an error, or that it was missed for any reason.

### Additional info

- Craft version: 4.5.14
- PHP version: 8.2
- Database driver & version: MySQL
- Plugins & versions: CKEditor 3.6.0, Redactor 3.0.4

**Comment by brandonkelly** [comment]
If you have a database backup from before the conversion, can you please revert and try again, but run `craft project-config/rebuild` first?
