### ISSUE TITLE
[4.0.0-beta.1] "New Entry" flow allows switching to unpermitted entry types within slideout

### ISSUE THREAD

**Issue by Mosnar** [craftcms/ckeditor#157]
### Description

Using the new "Create Entry" button, I'm able to bypass the entry type limitations defined in the config by opening the new entry slide-out and changing the type within the entry type dropdown.

For example, in this screenshot, I'm supposed to only be allowed to use "Call to Action" entry types.

![CleanShot 2024-02-07 at 13 58 09](https://github.com/craftcms/ckeditor/assets/3810939/fa3ff8b5-afb1-4ae6-a818-5f945304ce7f)

### Additional info

- Craft version: 5.0.0-alpha.13

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released 4.0.0-beta.3 with a fix.
