### ISSUE TITLE
Update to CKEditor 5 from alpha

### ISSUE THREAD

**Issue by Mosnar** [craftcms/ckeditor#16]
Now that CKEditor 5 is officially released, this repository should be updated from the alpha 2 build.

**Comment by sokolovstas** [comment]
Can be fixed with #19

**Comment by brandonkelly** [comment]
We just released version 1.0.0 of the plugin, which uses CKEditor 5 (27.0.0) by default, but you can supply any CKEditor build you want now (including v4 if needed).
