### ISSUE TITLE
Error after 3.7.2: cannot read properties of undefined (reading 'registerChildCommand')

### ISSUE THREAD

**Issue by thomascoppein** [craftcms/ckeditor#161]
### Description
After updating to 3.7.2 all the CKEditor fields are gone, only the label is visible. In console there is an error:
TypeError: Cannot read properties of undefined (reading 'registerChildCommand') at indentBlock.js:89:23.

### Steps to reproduce

1. Update CKEditor to 3.7.2
2. Open entry with CKEditor fields

### Additional info

- Craft version: 4.7.2
- PHP version: 8.2
- Database driver & version: mysql
- Plugins & versions: matrixmate (2.1.4), super-table (3.0.12)

**Comment by garethjohnsdesign** [comment]
Yes I had the same issue here, rolling back to 3.7.1 fixes this but the data was lost for some reason at least in Matrix blocks.

**Comment by Antimated** [comment]
Yep same issue getting this error in the console

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'registerChildCommand')
    at $a.afterInit (indentblock.js:89:23)`

Points to this:
![Screenshot 2024-02-08 at 12 05 50](https://github.com/craftcms/ckeditor/assets/2869409/367e47ba-e782-4cc6-a59c-56a1f2d06f5a)

**Comment by i-just** [comment]
Hi All, thanks for reporting! We fixed it this morning, but it has not yet been released. We'll update this issue as soon as the release is out!

**Comment by brandonkelly** [comment]
Sorry all. 3.7.3 is tagged now with the fix.

**Comment by brandonkelly** [comment]
@kevinmu17 That setting was removed in 3.7.0 (see #148).
