### ISSUE TITLE
Richtext Editor missing after Update to version 3.7.2

### ISSUE THREAD

**Issue by handplant** [craftcms/ckeditor#162]
After the update to version 3.7.2, all CKEditor text fields are no longer present. After downgrading to version 3.7.1, they reappear.

Javascript Error
`indentblock.js:89 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'registerChildCommand') at $a.afterInit (indentblock.js:89:23)`

![Bildschirmfoto 2024-02-08 um 12 28 42](https://github.com/craftcms/ckeditor/assets/2598962/acef1fca-380b-4ac3-a25d-754f1c269ef8)

**Comment by i-just** [comment]
Hi, thanks for reporting. It’s already been reported here: https://github.com/craftcms/ckeditor/issues/161, so I will close this one. Feel free to follow along on #161.
