### ISSUE TITLE
Multiple warnings in console after updates Craft CMS 4.7.3 and CKEditor 3.7.3

### ISSUE THREAD

**Issue by yingban** [craftcms/ckeditor#168]
### Description

I just updated the Craft CMS and CKeditor, and I got the following warnings in the console for each CKEditor fields:

![Screenshot 2024-02-19 at 15 04 48](https://github.com/craftcms/ckeditor/assets/3421450/e1633824-96a6-480c-b7e4-00c1885d58f5)

### Steps to reproduce

1. Update Craft to 4.7.3 and CKEditor to 3.7.3
2. Open an entry with a CKEditor field.

### Additional info

- Craft version: 4.7.3
- PHP version: 8.1.27
- Database driver & version: MySQL 8.0.32
- Plugins & versions: CKEditor 3.7.3

**Comment by brandonkelly** [comment]
CKEditor 3.8.0 is out now, which fixes these JavaScript warnings (via #171).
