### ISSUE TITLE
Fields’ isEmpty() method has been deprecated. Use isValueEmpty() instead.

### ISSUE THREAD

**Issue by jacobgraf** [craftcms/ckeditor#17]
### Description
Deprecation error in CP. Does not appear to be plugin-related, but core.

### Steps to reproduce

1. Look in deprecation logs to find error...

`Fields’ isEmpty() method has been deprecated. Use isValueEmpty() instead.`

### Additional info

- Craft version: Craft Solo 3.1.24
- PHP version: 7.1.26
- Database driver & version: MySQL 5.7.25
- Plugins & versions:

CKEditor 1.0.0-beta.2
Craft Commerce 2.1.3.1
Events 1.0.1
Field Manager 2.0.5
Linkit 1.1.11
SEOmatic 3.1.49
Smith 1.0.0
Sprout Active 2.0.9
Stripe for Craft Commerce 1.2.1

### Stack Trace

https://pastebin.com/PrKDaADG

**Comment by brandonkelly** [comment]
Thanks! Transferred your issue to that repo.

**Comment by EpocSquadron** [comment]
For those looking for a resolution, this was solved in a forked repo by @reilnuud: reilnuud/ckeditor@dd1fe3ab024fada6b872f3e2b2a3cfcf487ba359

**Comment by brandonkelly** [comment]
Just released CKEditor 1.0.0-beta.3 with a fix for this.
