### ISSUE TITLE
Anchor Links option not available

### ISSUE THREAD

**Issue by alexkuzmin** [craftcms/ckeditor#170]
### Discussed in https://github.com/craftcms/ckeditor/discussions/169

For the successful application of the WCAG 2.1 standard guidelines as outlined here https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html, there's a requirement for the capability to establish anchor links. Currently, this functionality is not available within the CKEditor plugin for CraftCMS. However, it's this feature has been successfully integrated into the Redactor Plugin: https://plugins.craftcms.com/redactor-anchors?craft4=. Considering this, could a similar implementation be feasible for the CKEditor plugin? Thanks.

**Comment by brandonkelly** [comment]
Closing in favor of #169.
