### ISSUE TITLE
[4.0] Unable to initialize field without Element

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/ckeditor#181]
### Description

When initializing ckeditor with this sort of code :

```
use craft\ckeditor\Field;

$config = [
    'type' => Field::class,
    'name' => 'Body',
    'handle' => 'body',
    'ckeConfig' => $ckeConfig
];
$field = \Craft::$app->fields->createField($config);
return $field->getInputHtml($someValue, null);
```
And passing `null` as element, an Error exception is thrown on line [883](https://github.com/craftcms/ckeditor/blob/4.0/src/Field.php#L883): `$value = $this->_prepNestedEntriesForDisplay($value, $element->siteId, $static);` as the `$element` is `null`

### Additional info

- Craft version: 5.0.0-beta.3
- PHP version: 8.2

**Comment by brandonkelly** [comment]
CKEditor 4.0.0-beta.8 is out with a fix for this (#182).
