### ISSUE TITLE
Styles dropdown preview broken

### ISSUE THREAD

**Issue by knufri** [craftcms/ckeditor#184]
### Description
When I add a custom style and then want to select it in the dropdown the preview is totally broken 

### Steps to reproduce

1. Add a custom style in the config
2. Try to select the style in the dropdown

### Additional info

- Craft version: 4.8
- PHP version: 8.2.16
- Plugins & versions: CKEditor | 3.8.0

<img width="1335" alt="Bildschirmfoto 2024-03-05 um 17 56 07" src="https://github.com/craftcms/ckeditor/assets/2785206/b2dd9beb-8675-45cd-af57-266d40bfed6a">

<img width="564" alt="Bildschirmfoto 2024-03-05 um 17 56 28" src="https://github.com/craftcms/ckeditor/assets/2785206/9b2e819b-8aa3-41ae-9404-007d05981527">

<img width="515" alt="Bildschirmfoto 2024-03-05 um 17 56 33" src="https://github.com/craftcms/ckeditor/assets/2785206/1b45217a-211e-4444-ae1d-ee81385db866">

**Comment by i-just** [comment]
Hi, thanks for reaching out! I can’t replicate this issue. In the screenshots you provided, is that the entire configuration you’re using for this CKEditor config? Do you see any errors in the console? Also, could you please confirm if you’re using any other plugins?

<img width="1104" alt="Screenshot 2024-03-14 at 14 30 39" src="https://github.com/craftcms/ckeditor/assets/4500340/1349f2f5-b9f5-4f8d-a97e-676629933d18">
