### ISSUE TITLE
[4.x] New Entry dropdown defaults to alphabetical ordering instead of the order set in field settings

### ISSUE THREAD

**Issue by brionwolf** [craftcms/ckeditor#185]
### Description

New Entry dropdown defaults to alphabetical ordering instead of the order set in field settings. _Not sure if this should go in the cms repo or here, but starting here._

### Steps to reproduce

1. Create a CKEditor field, and configuration. Make sure the configuration includes the "New Entry" button.
2. Add several entry types to the CKEditor field, in a specific order that isn't alphabetical or numerical _(ie: order of importance to content authors)_.
3. Add the field to a section and create/edit an entry for that section.
4. Click the "New Entry" dropdown button in the CKEditor field.

#### Expected Result:

- The list of entry types is in the order set from the field settings panel.

#### Actual results

- Available entry types are listed in alphabetical order.

### Screenshots

Field Settings Entry Type Selection:
<img width="406" alt="screencapture of the entry types list on the field settings panel of a CKEditor type field" src="https://github.com/craftcms/ckeditor/assets/5532234/edfa333c-8314-4a28-b90a-2262c07381c8">

Control Panel Field Example:
<img width="246" alt="Screenshot of the New Entry dropdown of A CKEditor field where all the entry types are in alphabetical order instead of the desired order" src="https://github.com/craftcms/ckeditor/assets/5532234/66cff578-d1d7-447e-bffc-f5755c162cc6">

### Additional info

- Craft version:  Craft Pro 5.0.0-beta.6
- PHP version: 8.3.1
- Database driver & version: MySQL 8.2.0
- Plugins & versions: 
    - CKEditor | 4.0.0-beta.7

**Comment by brandonkelly** [comment]
CKEditor 4.0.0-beta.8 is out with a fix for this. Thanks for reporting!

**Comment by brionwolf** [comment]
Working like a charm, Thank you @brandonkelly!

<img width="291" alt="Screenshot 2024-03-11 at 10 44 36 AM" src="https://github.com/craftcms/ckeditor/assets/5532234/610d26f3-1319-4e27-a74f-66a2f8e61b85">
