### ISSUE TITLE
[4.x] Editing copy/pasted embed entries will edit both the original and copied entry

### ISSUE THREAD

**Issue by brionwolf** [craftcms/ckeditor#186]
### Description

Editing copy/pasted embed entries will edit both the original and copied entry. _(I'm not sure if this should be added to the CMS repo or here, but I'm starting here)_.

### Steps to reproduce

1. Create and add a CKEditor field with embeddable entries to a section or other layout
2. Create or edit an entry that includes the CKEditor field.
3. Add an emebeded entry from the "New Entry" dropdown in the CKEditor field.
4. Select, copy, and paste the newly created entry as a second embeded entry in the CKEditor field.
5. Attempt to modify the second embeded entry.

#### Expected Result

- The newly created entry that was copy/pasted from the original is modified while the original is not.

#### Actual results

- Both the original entry, and the newly created entry are modified based on subsequent changes to either entry.

### Screenshots

**Example CKEditor field with a simple entry type:**
![Copying an embedded entry within a CKEditor field](https://github.com/craftcms/ckeditor/assets/5532234/073dea1e-3e85-4f37-b5d2-5d30f1e1dbb5)

**Workaround:**
![Creating a new emedded entry in a CKEditor field](https://github.com/craftcms/ckeditor/assets/5532234/5d3e1fb0-c8b7-4d82-abe8-6e7c387b195b)
- Manually creating a separate entry from the "New entry" dropdown does not trigger this duplicating effect.

### Additional info

- Craft version: Craft Pro 5.0.0-beta.6
- PHP version: 8.3.1
- Database driver & version: MySQL 8.2.0
- Plugins & versions:
    - CKEditor | 4.0.0-beta.7

**Comment by brandonkelly** [comment]
Those cards are just references to the nested entries. If you copy/paste the card, you’re just creating a second reference to it; not actually duplicating the nested entry. We’ll discuss internally whether we should make it impossible to duplicate the cards in the first place, to help avoid that confusion.

**Comment by brandonkelly** [comment]
We just tagged version 4.0.0, which adds support for automatically duplicating nested entries when entry cards are copy/pasted. (#192)

**Comment by brionwolf** [comment]
Thank you @brandonkelly @i-just! Works great, and our content authors will love it!

<img width="800" alt="Screenshot 2024-03-15 at 4 48 46 PM" src="https://github.com/craftcms/ckeditor/assets/5532234/ecb4d402-0897-4acf-a0dc-9348dfdbb978">
