### ISSUE TITLE
Element without getFieldLayout results in an error

### ISSUE THREAD

**Issue by GewoonRoy** [craftcms/ckeditor#190]
### Description
I made a custom Element within CraftCMS which doesnt have a getFieldLayout function defined. So when the custom Element is being saved and propagated then it will call the craft\base\Element::getFieldLayout() function. This function has a return value of FieldLayout or `null`.

The `Element::EVENT_AFTER_PROPAGATE` event is being called within the CKEditor plugin. It then tries to loop through `$element->getFieldLayout()?->getCustomFields()`, which is `null` in my case, and then the error occurs.

```
Exception^ {
  #message: "foreach() argument must be of type array|object, null given" 
  #code: 2
  #file: "./vendor/craftcms/ckeditor/src/Plugin.php"
  #line: 134
  #severity: E_WARNING
  trace: {
    ./vendor/craftcms/ckeditor/src/Plugin.php:134 { …}
    ./vendor/craftcms/ckeditor/src/Plugin.php:103 { …}
    craft\ckeditor\Plugin->craft\ckeditor\{closure}() {}
    ./vendor/yiisoft/yii2/base/Event.php:312 { …}
    ./vendor/yiisoft/yii2/base/Component.php:642 { …}
    ./vendor/craftcms/cms/src/base/Element.php:5709 { …}
    ./vendor/craftcms/cms/src/services/Elements.php:3717 { …}
    ./vendor/craftcms/cms/src/services/Elements.php:1168 { …}
    ./vendor/craftcms/cms/src/services/Elements.php:3488 { …}
    ./vendor/craftcms/cms/src/services/Elements.php:1249 { …}
    ...
  }
}
```

### Steps to reproduce

1. Create a custom Element and do not defined the getFieldLayout function
2. Call `Craft::$app->getElements()->saveElement($customElement)`
3. An error will occur

### Additional info

- Craft version: 5.0.0-beta.6
- PHP version: 8.3
- Database driver & version: MySQL8.2
- Plugins & versions:  CraftCMS/CKEditor 4.0.0-beta.9

**Comment by brandonkelly** [comment]
Thanks for reporting that! I’ve fixed it for the next release.

**Comment by brandonkelly** [comment]
CKEditor 4.0.0-beta.10 is out with that fix. Note that it requires Craft CMS 5.0.0-beta.7 or later, so you will need to update that first before the CKEditor update shows up in the Updates utility, if using.
