### ISSUE TITLE
[4.x] Images/assets button is missing from configurable ckeditor selection of toolbar items

### ISSUE THREAD

**Issue by brionwolf** [craftcms/ckeditor#195]
### Description

Images/assets button is missing from configurable ckeditor selection of toolbar items

### Steps to reproduce

1. Add/update ckeditor to latest version (4.0.0)
2. Navigate to Settings > CKEditor
3. Open and existing or create a new ckeditor configuration
4. Attempt to add the "Image/Assets" button to the selection of toolbar items, but the option is missing.

Screenshots:

<img width="1033" alt="Screen-capture of the CraftCMS CKEditor configuration dashboard" src="https://github.com/craftcms/ckeditor/assets/5532234/0c3df0de-42c1-4915-9507-f7bcde097118">

### Additional info

- Craft version: Craft Pro 5.0.0-beta.7
- PHP version: 8.3.1
- Database driver & version: MySQL 8.2.0
- Plugins & versions:
    - CKEditor | 4.0.0

### Workaround

- Create an entryType with an assets field, to add assets via nested entries.

**Comment by kerrig** [comment]
Seeing this same thing on these versions:
- Craft version: Craft Pro 4.8.3
- PHP version: 8.2
- Database driver & version: MariaDB 10.5.1
- CKEditor | 3.8.1

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
v4.0.2 is out now with a fix for this. Thanks again!

**Comment by kerrig** [comment]
@brandonkelly could we also get a fix for 3.8.1?

**Comment by brandonkelly** [comment]
@kerrig Sorry! Missed that this also affected v3. 3.8.2 is out now with the same fix.

**Comment by brionwolf** [comment]
Late to the game, but confirming, fixed in latest. Thanks for this!
