### ISSUE TITLE
Linking to Craft Entry appends persistent hashtag #entry:77@1:url

### ISSUE THREAD

**Issue by akukral** [craftcms/ckeditor#197]
### Description
When adding links within the CKEditor field via the link dropdown to an internal existing entry page the hashtag appended to the URL persists when rendering in a front-end template.

Previously as an example in CKEditor v 3.8.1 this #entry: hashtag was stripped when rendering in a template.

### Steps to reproduce

1. Highlight text in rich text field.
2. Click dropdown for link
3. Click link to entry
![image](https://github.com/craftcms/ckeditor/assets/413115/781c549e-2f75-497c-9c5c-a355588a54e9)
4. Select entry and confirm
5. Check link URL in CKEditor, confirm existence of #entry: hashtag
![image](https://github.com/craftcms/ckeditor/assets/413115/06df6e37-0da6-4d3c-b991-6da060111a41)
6.  Save entry
7. Check template rendered with {{ entry.excerpt }}
8. Link/URL to the entry is correct though the #entry:77@1:url appended in the rich text field persists.

### Additional info

- Local setup ddev version v1.22.7 
- Craft version: 5.0.0-beta.10
- PHP version: 8.2.15
- Database driver & version: MySQL 8.0.33
- Plugins & versions: 
CK Editor: 4.0.x-dev
Embedded Assets 5.0.0-beta.1
Freeform 5.1.4
Minify v5.x-dev
SEOmatic v5.x-dev

- CK Editor Config
``
return {
  style: {
    definitions: [
      {
        classes: [
          'brand-blue',
        ],
        element: 'span',
        name: 'Brand Blue',
      },
    ],
  },
}
``

**Comment by mfell** [comment]
I can confirm this: Craft 5.0.1 // CKEditor 4.0.3

**Comment by akukral** [comment]
Until this is addressed I'm using this javascript code to strip this out on the front end to some effect. 

```
function rewriteLinks(stringToStrip) {
  // Regular expression to match the string to strip with optional delimiters
  const regex = new RegExp(`(?:/|\\?|&)?${stringToStrip}(?:/|\\?|&)?`, 'g');

  const links = document.querySelectorAll('a');

  for (const link of links) {
    const href = link.href;
    const newHref = href.replace(regex, '');

    // Check if the URL changed to avoid unnecessary modifications
    if (href !== newHref) {
      link.href = newHref;
    }
  }
}

rewriteLinks('#entry:(.*?):url');
```

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
CKEditor 4.0.4 is out with a fix for this. Thanks again!
