### ISSUE TITLE
Is this plugin officially abandoned?

### ISSUE THREAD

**Issue by EpocSquadron** [craftcms/ckeditor#20]
The last release was in January 2018, even though there are commits through march this year. We do actually make use of this. Should we be migrating away from it?

**Comment by verbeeksteven** [comment]
I have a version at https://github.com/HAWK-Marketing/ckeditor with all of the prs merged and images + internal link button added with craftcms setup.

Toolbar commands are

insertInternalLink
insertImage

The regular image can be removed, but leave link and add insertInternalLink beside it.

At the moment there isn't an easy way to create a "dropdown" and let them select Link to Entry, Link to Category, External Link, etc like froala editor is done. I am going to continue to investigate options and see if rewriting the link plugin itself would be a good option.

**Comment by adrienne** [comment]
@verbeeksteven - is there a way to install your version via Composer or do we have to manually copy the files?

**Comment by thejoshsmith** [comment]
@adrienne we are maintaining a version here: https://github.com/batchnz/craft-ckeditor which you can install with `composer require batchnz/craft-ckeditor` 😄

**Comment by brandonkelly** [comment]
We just released version 1.0.0 of the plugin, and plan to make it a bigger focus of ours going forward, due to CKEditor’s significant accessibility advantages over Redactor.
