### ISSUE TITLE
Failed to run php craft ckeditor/convert: exit status 1

### ISSUE THREAD

**Issue by CreateSean** [craftcms/ckeditor#200]
### Description
Installed CKeditor so I can migrate from redactor. When I run the CLI command `php craft ckeditor/convert` I get the following error message.

```
λ ddev php craft ckeditor/convert
Unknown command: ckeditor/convert
Caused by: Exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "ckeditor/convert".'    

in /var/www/html/vendor/yiisoft/yii2/base/Module.php:561     

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('ckeditor/conver...', Array)#1 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('ckeditor/conver...', Array)
#2 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('ckeditor/conver...', Array)
#3 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#4 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#5 /var/www/html/craft(13): yii\base\Application->run()      
#6 {main}
Failed to run php craft ckeditor/convert: exit status 1
```

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 4.7.4
- PHP version:8.2.15
- Database driver & version:mysql 8.0
- Plugins & versions:

**Comment by green17** [comment]
We get the same problem.

**Comment by brandonkelly** [comment]
Go to **Settings** → **Plugins** and make sure that CKEditor is installed first. Or run the following command:

```sh
php craft plugin/install ckeditor
```

**Comment by CreateSean** [comment]
plugin was installed, but uninstalling and re-installing fixed it.

**Comment by thom-moresoda** [comment]
I'm having similar issues, although re-installing didn't resolve anything 

Craft version: 3.9.4
PHP version: 7.4

```
ddev craft ckeditor/convert       
Unknown command: ckeditor/convert
Caused by: Exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "ckeditor/convert".'

in /var/www/html/vendor/yiisoft/yii2/base/Module.php:561

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('ckeditor/conver...', Array)
#1 /var/www/html/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('ckeditor/conver...', Array)
#2 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('ckeditor/conver...', Array)
#3 /var/www/html/vendor/craftcms/cms/src/console/Application.php(118): yii\console\Application->handleRequest(Object(craft\console\Request))
#4 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#5 /var/www/html/craft(22): yii\base\Application->run()
#6 {main}
Failed to run craft ckeditor/convert: exit status 1

```

**Comment by alexmglover** [comment]
I am having the same issue as well, and uninstalling/reinstalling didn't work.

Craft Version: 3.9.13
Php Version: 8.1.27

**Comment by patrickcanlas-psandco** [comment]
Similar issue here as well. Uninstall/reinstall did not work.

CKEditor Version: 1.5.0
Craft Version: 3.9.13
PHP Version: 7.4
MySQL Version: 5.7

**Comment by alexmglover** [comment]
Not sure how I overlooked this, but I realized the convert command doesn't exist in CKeditor 1.5.0. I have been working on manually converting using the Javascript initialization field.

**Comment by patrickcanlas-psandco** [comment]
> Not sure how I overlooked this, but I realized the convert command doesn't exist in CKeditor 1.5.0. I have been working on manually converting using the Javascript initialization field.

@alexmglover how do you do it?

**Comment by thom-moresoda** [comment]
@brandonkelly is the convert command only available in later versions of ckeditor? eg. I'll need to update craft to v4 first

**Comment by brandonkelly** [comment]
`ckeditor/convert` wasn’t added until CKEditor 3.1.0, so you will need to update to at least that version before running it. (If you’re upgrading to Craft 5 + CKEditor 4.x, you could also wait and run it after the upgrade.)

**Comment by jonathanbright** [comment]
I have version 3.8.3 of the CKEditor plugin and running "php craft ckeditor/convert" returns "Unknown command: ckeditor/convert"

**Comment by masiorama** [comment]
> > Not sure how I overlooked this, but I realized the convert command doesn't exist in CKeditor 1.5.0. I have been working on manually converting using the Javascript initialization field.
> 
> [@alexmglover](https://github.com/alexmglover) how do you do it?

I quote @patrickcanlas-psandco , @alexmglover how did you solve it?
