### ISSUE TITLE
Custom Config Not Appying to Field

### ISSUE THREAD

**Issue by zadro** [craftcms/ckeditor#202]
### Description

Maybe I'm not doing something properly, as I'm new to CK Editor. I tried to update a Redactor field to a CK Editor field and, at the same time, created a new CK Editor config.  The CK Editor interface does NOT have the fields from the config.

![Screenshot 2024-04-03 at 4 41 38 PM](https://github.com/craftcms/ckeditor/assets/2326478/cacffe78-d39e-4f63-bf5e-a21676f1d54a)
![Screenshot 2024-04-03 at 4 41 55 PM](https://github.com/craftcms/ckeditor/assets/2326478/30e33bc4-faf6-4a5e-982c-2690470a6137)
![Screenshot 2024-04-03 at 4 42 11 PM](https://github.com/craftcms/ckeditor/assets/2326478/bfc38a7d-3f06-45a8-a96c-48d2d0394cdf)

### Steps to reproduce

1. Create custom config in GUI
2. Apply custom config to field
3. View field for new interface features (not there)

### Additional info

PHP version 	8.1.27
OS version 	Linux 6.1.0-18-amd64
Craft version 	Craft Pro 4.8.6

### Plugins
CKEditor 	3.8.3
Super Table 	3.0.12

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I'm having trouble replicating this. Do you see any errors in the console?

**Comment by zadro** [comment]
No errors are being displayed. To troubleshoot further, I created a **new** CKEditor field and attached the config -- this new field shows the config options correctly.

_So, the issue appears to be with converting a Redactor field to a CK Editor field and its config association._ 

What I did next was convert the field **back** to Redactor, then used `php craft ckeditor/convert` to convert the field to CKEditor. Success!

Not sure if this is explained somewhere that I missed, but properly converting the field is necessary.

**Comment by i-just** [comment]
Thanks for all the info! So, to be clear, when you said you first converted the field and then converted it properly (via the `php craft ckeditor/convert` command), do you mean that the first time, you didn’t go via the command?

**Comment by zadro** [comment]
Of course! Please note that I would not have known about the `convert` command if I hadn't been part of this discussion: https://github.com/craftcms/redactor/issues/489#issuecomment-2035270493

In the first attempt, I did not convert the field. I updated the field type (dropdown). Then, after learning about the convert utility and your reply that you couldn't replicate it, I thought to try it.

**Comment by i-just** [comment]
Right, thanks! I also tried switching the field type via the dropdown, and that worked okay for me. Anyway, the command is there to take the hassle out of converting, and I’m glad to hear it’s working as expected for you. 

I will close this now, but feel free to reach out if you run into any more problems.
