### ISSUE TITLE
FR: MODIFY_PURIFIER_CONFIG

### ISSUE THREAD

**Issue by ishetnogferre** [craftcms/ckeditor#204]
### Description
For the Redactor field, we had the option to modify the purifier config via the [MODIFY_PURIFIER_CONFIG](https://github.com/craftcms/redactor?tab=readme-ov-file#html-purifier-configs) event. I was wondering if we could have the same for CKEditor or is there another way to modify this?

We like to migrate a Redactor field to CKEditor but are losing, in this case, some data-attributes, we've added via this event.

Some context on what we're doing:
```
Event::on(
                RedactorField::class,
                RedactorField::EVENT_MODIFY_PURIFIER_CONFIG,
                function (Event $event) {
                    if( $event->config ) {
                        if( $def = $event->config->getDefinition('HTML', true) ) {
                            // http://htmlpurifier.org/docs/enduser-customize.html#addAttribute
                            $def->addAttribute('a', 'data-track-name', 'Text');
                            $def->addAttribute('a', 'data-track-id', 'Text');
                            $def->addAttribute('a', 'data-track-follow', 'Text');
                        }
                    }
                }
            );
```

Thanks!

**Comment by i-just** [comment]
Hi, thanks for reaching out. The same event exists for the CKEditor: https://github.com/craftcms/ckeditor?tab=readme-ov-file#html-purifier-configs.

Hope this helps!

**Comment by ishetnogferre** [comment]
Oh, apologies, looked over that!

Although the event is there and the Purifier config is extended in the same way as the Redactor one, the config still doesn't seem to be applied (in this case) 🤔 Gonna debug a little more to see if I can pinpoint where it's different in this case.

**Comment by ishetnogferre** [comment]
In this case we also had to edit the General HTML Support setting in the config of the CKEditor field: https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html#enabling-all-html-features
