### ISSUE TITLE
Nested entries lost when running resave entries command

### ISSUE THREAD

**Issue by d-karstens** [craftcms/ckeditor#211]
### Description
Hi,

We've encountered an issue where nested entries are removed when using the `craft resave/entries` command. 
We initially encountered it with a nested entry containing only a Hyper field, where when we run the resave entry command it seems to keep the link, but is no longer registered as a nested entry and some xml data is added

Before running the command:
<img width="591" alt="Screenshot 2024-04-22 at 5 01 04 PM" src="https://github.com/craftcms/ckeditor/assets/21274925/4d288474-ff80-49e5-aab4-a8178fa2a4d2">

<img width="679" alt="Screenshot 2024-04-22 at 5 00 55 PM" src="https://github.com/craftcms/ckeditor/assets/21274925/9620409e-7230-43c7-ba83-87f1aae9584d">

After running the command:
<img width="590" alt="Screenshot 2024-04-22 at 5 01 49 PM" src="https://github.com/craftcms/ckeditor/assets/21274925/ee682ea9-296a-44e7-8212-b794f71f1887">

To check if this was an issue with the Hyper plugin or CKEditor, I made a nested entry containing only an image field and after running the resave command the nested entry is removed entirely - so it seems to be a CKEditor issue

Before running the command: 
<img width="584" alt="Screenshot 2024-04-22 at 5 09 23 PM" src="https://github.com/craftcms/ckeditor/assets/21274925/96c91ae7-99f4-467d-94eb-fc5a062f70a3">

After running the command:
<img width="586" alt="Screenshot 2024-04-22 at 5 11 12 PM" src="https://github.com/craftcms/ckeditor/assets/21274925/663908d6-5db7-40a1-85c8-78cc5986f483">

### Steps to reproduce

1. Create a CKEditor field with a nested entry containing an image field
2. Run `craft resave/entries` and nested entry is lost

### Additional info
Our nested entries have associated partial templates, but without those the nested entries are still deleted

- Craft version: 5.0.4
- PHP version: 8.2.18
- Database driver & version: MySQL 8.0.33
- Plugins & versions: CKEditor: 4.0.3, Hyper: 2.0.0-beta.8

**Comment by brandonkelly** [comment]
Thanks for reporting that! CKEditor 4.0.4 is out with a fix.
