### ISSUE TITLE
Missing documentation about oembed in Redactor->CKEditor

### ISSUE THREAD

**Issue by KevinBodi** [craftcms/ckeditor#213]
### Description

Redactor used `<iframe>`-tags for embedding while CKEditor uses a `<oembed>`-tag. When a site supports embedding in their rich text editors existing embeds that were in the database before migrating will also work as supposed after migrating, but when using CKEditor to add new embeds it won't render without any extra configs to make it work.

I suppose there is some extra work that must be done to make this work, that isn't described in the documentation.
Edit: We needed iframely or Embedly installed in the frontend

### Steps to reproduce

1. Migrate from Redactor to CKEditor
2. Use the rich text editor to add new embeds after migrating
3. The embed or video doesn't appear when it used to do so in Redactor

**Comment by i-just** [comment]
Hi, thanks for reaching out! Yes, CKEditor uses `oembed` tags for media content. We’ve explained what needs to be done to support embedding media here: https://github.com/craftcms/ckeditor?tab=readme-ov-file#embedding-media. 
I hope this helps! 

I’ll close this now, but feel free to reach out if I misunderstood what you were after.

**Comment by KevinBodi** [comment]
Hi, @i-just!

That oembed-tag is exactly the issue with migrating from Redactor (which you don't support anymore in the future) to CKEditor as it seems like the only point of the migration from Redactor where existing content and functionality (eg. iframes made before migrating) is broken from the editors view. Fortunately it doesn't affect how already published content looks in frontend.

It's easy for a developer to not catch this when they only read the migration part of the documentation and when testing after migrating one might not catch this until editors notice it not working, when everything else does. The other thing is that the migration script automatically replaces the "Redactor Embed" (that takes HTML) with the "CKEditor Media Embed" (that takes URLs instead and requires paid or branded front-end scripts). Because replacing "Redactor Embed" with "CKEditor Media Embed", one might expect that it's the same thing.

However, we found out that "CKEditor HTML Embed" (not same as Media Embed) has behaviour that's more similar to how Redactor works. The only difference that must be taken account for in frontend is that the formatting that was
```
<figure>
   <iframe />
</figure>
```
is now
```
<div class="raw-html-embed">
   <iframe />
</div>
```
instead of
```
<oembed url="..." />
```

**Comment by i-just** [comment]
Right, I get your point now; thanks! We’ll have a look at updating the docs.
