### ISSUE TITLE
Invalid Entry ID when adding a nested entry after upgrading to 4.0.5

### ISSUE THREAD

**Issue by AdamChlan** [craftcms/ckeditor#229]
Since upgrading to version 4.0.5 today, any time we add a nested entry to a ckeditor field, it returns with a message "Invalid Entry ID: (id number)". I noticed a fix for a similar issue was a part of today's patch, but prior to this release we were not seeing the behavior we are seeing now.

### Additional info

- Craft version:  5.1.3
- PHP version: 8.2
- Database driver & version: mysql 8.0
- Plugins & versions:
```
    "craftcms/ckeditor": "4.0.5",
    "craftcms/cms": "5.1.3",
    "craftcms/postmark": "^3.1.0",
    "nystudio107/craft-retour": "5.0.0",
    "nystudio107/craft-seomatic": "5.0.2",
    "nystudio107/craft-vite": "5.0.0",
    "putyourlightson/craft-sherlock": "5.0.0",
    "putyourlightson/craft-sprig": "3.0.1",
    "verbb/knock-knock": "3.0.0",
```

**Comment by brandonkelly** [comment]
Hey, thanks for reporting that. Just released 4.0.6 with a fix.
