### ISSUE TITLE
New Config is not showing in editor

### ISSUE THREAD

**Issue by dhirajsah** [craftcms/ckeditor#230]
So i created the new config for my ck editor and saved/applied it to editor from Fields section,

But new config in toolbar not showing in the editor in entries, or whereever editor filed is called,

only showing 'heading', '|', 'bold', 'italic', 'link'

need help on the same, 

--
Thanks

-----------------------------
Craft version: 4.9.3
PHP version: 8.0.2
Database driver & version: mysql 8

**Comment by i-just** [comment]
Hi, thanks for reaching out! To clarify, after creating the new config, did you assign it to the CKEditor field(s)?

**Comment by dhirajsah** [comment]
Hi,

Yes, i also tried changing different config, its not applying

please check

![ck-editor-error](https://github.com/craftcms/ckeditor/assets/8079755/e6659efb-1bdd-4733-962e-c639ab7d7a0d)

![image](https://github.com/craftcms/ckeditor/assets/8079755/b0395219-3fba-4ba6-aafa-60934d86c57d)

**Comment by i-just** [comment]
Thanks for confirming! So, what’s the setup of that “Full” config? Do you see any errors in the console when you edit the config or when you view the page that contains that CKEditor field?

**Comment by dhirajsah** [comment]
Not the error but the warning i guess, pls check below

![image](https://github.com/craftcms/ckeditor/assets/8079755/febebcd9-918c-4789-ae07-a7be8db67c77)

![image](https://github.com/craftcms/ckeditor/assets/8079755/0f444cd7-6eca-48a7-aaa9-8c926a5fe7c2)

**Comment by i-just** [comment]
Thanks! I’m unable to replicate this. Could you please send your `composer.json`, `composer.lock` and `config/project` directory to support@craftcms.com so that I can dig deeper?

**Comment by dhirajsah** [comment]
Hi,

Sent you the files and folders to support@craftcms.com please check.

**Comment by i-just** [comment]
Thanks! I replied via email, so I will close the GH issue. 

For postering, in this case, the affected fields needed to be resaved to apply the selected config correctly.

**Comment by dhirajsah** [comment]
Hi,

Yes, i had to resave all the ckeditor to apply that new config, it was selected but not saved in db i guess, 

now the selected items are showing in editor toolbar,

Thanks for your help..
