### ISSUE TITLE
Table property and cell property not showing

### ISSUE THREAD

**Issue by dhirajsah** [craftcms/ckeditor#235]
### Description

Hi,

Inserted table does not shows **Table property** and **Cell property**  need help showing them as we need to make some padding and spacing inside table data 

alos when inserting the table, it generate the **<figure class"table">** tag is it possible to not to have that figure tag

![image](https://github.com/craftcms/ckeditor/assets/8079755/3eda28ee-0524-4985-ae5b-35e46adcc790)

--
Thanks

### Additional info

- Craft version: 4.9.3
- PHP version: 8.3
- Database driver & version: 8
- Plugins & versions: 3.8.3

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

To include Table Properties and Table Cell Properties buttons alongside the default Table Row, Table Column and Merge buttons, you need to add `"tableProperties"` and `"tableCellProperties"` to the config options under `table` > `contentToolbar`. Here’s a link to a discussion that explains this a bit more: https://github.com/craftcms/ckeditor/discussions/115

> alos when inserting the table, it generate the <figure class"table"> tag is it possible to not to have that figure tag

This is how CKEditor renders tables. You could write something yourself to strip those out when rendering in the front end.

I hope this helps!

**Comment by dhirajsah** [comment]
👍

Thanks
