### ISSUE TITLE
Not able to drag items into toolbar

### ISSUE THREAD

**Issue by casvangrunsven** [craftcms/ckeditor#236]
### Description

When I try to choose a CKEditor config while editing or creating a field, I am not able to choose any fields in the toolbar. You can see the screenshot, with the console included. Seems like some javascript files are not being loaded. I already tried removing the plugin and adding again.

<img width="950" alt="image" src="https://github.com/craftcms/ckeditor/assets/33658765/2bfeba35-3968-49f7-a130-25702a5e9e03">

### Steps to reproduce

1. Create a field and choose CKEditor
2. Click on CKEditor config -> Create

### Additional info

- Craft version: Team 5.1.8
- PHP version: 8.2.11
- Database driver & version: MySQL 8.0.33
- Plugins & versions: 4.0.6

**Comment by SETU-WEB** [comment]
Hi 
I had the same problem and the solution is covered here https://github.com/craftcms/ckeditor/issues/150 , updating nystudio107/craft-code-editor solves the issue

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m having trouble replicating this error. 

Do you use any other plugins in this project? If so, could you please list them all (including the versions you use)?
If you go to Control Panel > Settings > CKEditor > New config, do you get the same errors in the console?

**Comment by casvangrunsven** [comment]
Hi,

It still remains at when I updated the "nystudio107/craft-code-editor" package. When I go to the settings > New config page, I get an other error. Attached are my screenshots for both Control Panel > Settings > CKEditor > New config and Control Panel > Settings > Fields > CkEditor field

Control Panel > Settings > CKEditor > New config 
<img width="1882" alt="Screenshot 2024-06-12 at 09 18 30" src="https://github.com/craftcms/ckeditor/assets/33658765/4f57f8fe-f5e1-4d7d-9862-eb0a870f8cf9">

Control Panel > Settings > Fields > CkEditor field
<img width="1901" alt="Screenshot 2024-06-12 at 09 20 38" src="https://github.com/craftcms/ckeditor/assets/33658765/3232999b-0d50-4d7b-85aa-30a72247084c">

Furthermore, the installed composer packages are the following:
"require": {
    "convergine/craft-content-buddy": "1.1.3",
    "craftcms/ckeditor": "^4.0.6",
    "craftcms/cms": "5.1.8",
    "mmikkel/cp-field-inspect": "2.0.1",
    "nystudio107/craft-code-editor": "^1.0",
    "nystudio107/craft-minify": "5.0.0",
    "nystudio107/craft-seomatic": "5.0.3",
    "spacecatninja/imager-x": "5.0.0",
    "spicyweb/craft-embedded-assets": "5.1.0",
    "topshelfcraft/environment-label": "5.0.0",
    "verbb/cloner": "3.0.0",
    "verbb/expanded-singles": "3.0.0",
    "verbb/formie": "3.0.0-beta.13",
    "verbb/hyper": "2.0.0",
    "verbb/image-resizer": "4.0.0",
    "verbb/navigation": "3.0.0",
    "verbb/smith": "3.0.0",
    "verbb/super-table": "4.0.0",
    "vlucas/phpdotenv": "^5.4.0"
  }
  
  Thanks!

**Comment by casvangrunsven** [comment]
> Hi
> I had the same problem and the solution is covered here #150 , updating nystudio107/craft-code-editor solves the issue

Hi,

Thanks for your response. This still does not seem to do the trick. Maybe I am updating it not in the right way.

**Comment by i-just** [comment]
Thanks for the update @casvangrunsven! I’m not able to replicate this. Would you be able to send your `composer.json`, `composer.lock` and db backup to support@craftcms.com so that we can try to dig deeper?

**Comment by casvangrunsven** [comment]
> Thanks for the update @casvangrunsven! I’m not able to replicate this. Would you be able to send your `composer.json`, `composer.lock` and db backup to [support@craftcms.com](mailto:support@craftcms.com) so that we can try to dig deeper?

Thanks, I just sent you the email!

**Comment by i-just** [comment]
Resolved in support.
