### ISSUE TITLE
Nested Entries Still Render On The Front End When Disabled

### ISSUE THREAD

**Issue by brianrivet-tilt** [craftcms/ckeditor#246]
### Description

If you create a nested entry and then disable it, it still renders on the front end.

### Steps to reproduce

1. Create a nested entry in CKeditor.
2. Disable it
3. View on front end

### Additional info

- Craft version: Pro 5.1.10
- PHP version: 8.2.13
- Database driver & version: MySQL 8.0.33
- Plugins & versions: CKEditor 4.0.6

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
CKEditor 4.1.0 is out now with that fix. Thanks again!
