### ISSUE TITLE
Changes are not saved in CKEditor field while in "source" mode.

### ISSUE THREAD

**Issue by yumpdevs** [craftcms/ckeditor#250]
### Description
Changes are not saved in CKEditor field while in "source" mode. For example I added style="color: red" in `<p>` tag 
(`<p style="color: red">`) 
and save the entry (or close the source mode), the style="color: red" will disappear and not saved in the CKEditor rich text field.

### Steps to reproduce

1. Go to an entry and edit the contents of a CKEditor field in "source" editing mode.
2. Add attributes (class, style, id or anything) into a tag (p tag I tried) in source mode.
3. Save the entry

### Expected behavior
The changes should be saved.

### Actual behavior
The changes are lost.

### Additional info

- Craft version: 4.10.0
- PHP version: 8.2
- Database driver & version:
- Plugins & versions: CKEditor 3.8.3

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Did you configure your field to allow styles to be added this way? This issue has info on how to do this: https://github.com/craftcms/ckeditor/issues/217

I’ll close this now, but feel free to reach out again if you run into any further problems.
