### ISSUE TITLE
Some HTML tags not Preserved in Migration from Redactor

### ISSUE THREAD

**Issue by zadro** [craftcms/ckeditor#258]
### Description

When attempting to convert from Redactor 4.1.0 to CKEditor 4.1.0, I find that some tags, specifically `pre` tags, are not preserved in the migration. 

### Steps to reproduce

Tried migrating in multiple ways. First, with a direct field change. Second, using `php craft ckeditor/convert` Neither option will preserve the `<pre>` tags within the field's HTML source. 

### Additional info

- Craft version: 5.2.3
- PHP version: 8.2.20
- Database driver & version: MariaDB 10.11.8
- Plugins & versions: 
Azure Blob Storage 	2.1.0
CKEditor 	4.1.0
Redactor 	4.1.0
SEO 	v5.0.0-rc4

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
CKEditor 3.9.0 and 4.2.0 are out with that fix. Thanks again!
