### ISSUE TITLE
Class attribute not retained with migration from Redactor

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/ckeditor#263]
### Description

When Redactor config is migrated to CKEditor config, the migration doesn’t include allowances for the `class` attribute.

```json
{
  "htmlSupport": {
    "allow": [
      {
        "attributes": true,
        "classes": true,
        "styles": true
      }
    ]
  }
}
```

### Additional info

- Craft version: 4.10.3
- PHP version: 8.3
- Database driver & version: MariaDB 10.3
- Plugin version: 3.8 (max for Craft 4.x)

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
CKEditor 3.9.0 and 4.2.0 are out with that change. Thanks again!
