### ISSUE TITLE
Condition rules result in errors on the edit forms

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/ckeditor#267]
### Description

Adding a display condition to a field layout element that depends on a CKEditor field results in an error message:

![Call to undefined method craft\ckeditor\data\FieldData::isEmpty()](https://github.com/craftcms/ckeditor/assets/10146880/bba96609-a36a-407f-8c30-d67516c3ff06)

The field seemingly provides condition rules for _element queries_, not for plain text fields. When the field is selected, the only two options are _has a value_ and _is empty_:

![entry-condition-ckeditor-field](https://github.com/craftcms/ckeditor/assets/10146880/db8f0709-6196-419b-9efe-d7523d55b006)

Instead of the usual options you get when selecting a plain text field:

![entry-condition-plaintext-field](https://github.com/craftcms/ckeditor/assets/10146880/4d81dbcf-9dc1-4dbc-abd5-927c2485f7d9)

On the entry form, the condition rule treats the `$value` as an element query or collection, that's causing an error.

### Steps to reproduce

1. Create a CKEditor field and any other field and add them both to an entry type's field layout.
2. Add an entry condition to the second field that depends on the CKEditor field.
3. Open the entry edit form.

### Additional info

- Craft version: 5.2.5
- PHP version: 8.3
- CKEditor version:  4.1.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised PRs to address this. 

At this point, the CKEditor field only supports the `EmptyFieldConditionRule` (“has a value”, “is empty”). Please post a new discussion if you think it should be extended beyond that.

**Comment by MoritzLost** [comment]
@i-just Thanks! The condition rules for empty/non-empty fields are sufficient for me, the other substring options rarely make sense for CKEditor fields.

**Comment by brandonkelly** [comment]
Craft 4.10.7 and 5.2.9 are out with that fix. Thanks again!
