### ISSUE TITLE
Not able to scroll in the link site selector

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/ckeditor#268]
### Description
Our project has a lot of sites, so many that you can't scroll in the link site selector. Ideally they should show the group name like the site selector on other places.
![image](https://github.com/craftcms/ckeditor/assets/22771556/a929de43-3328-4e51-8e84-10cbc9435737)

### Steps to reproduce

1. Have a lot of Craft sites
2. Try to change a link

### Additional info

- Craft version: 5.2.5
- PHP version: 8.3.7
- Database driver & version: MySQL 8.0.35
- Plugins & versions: CKEditor 4.1.0, ...

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
CKEditor 3.9.0 and 4.2.0 are out with that fix. Thanks again!
