### ISSUE TITLE
I have version 3.8.3 of the CKEditor plugin and running "php craft ckeditor/convert" returns "Unknown command: ckeditor/convert"

### ISSUE THREAD

**Issue by jonathanbright** [craftcms/ckeditor#271]
I have version 3.8.3 of the CKEditor plugin and running "php craft ckeditor/convert" returns "Unknown command: ckeditor/convert"

_Originally posted by @jonathanbright in https://github.com/craftcms/ckeditor/issues/200#issuecomment-2228993496_

**Comment by i-just** [comment]
Hi, thanks for reaching out. Can you please confirm that the CKEditor plugin is installed and enabled?

**Comment by jonathanbright** [comment]
Yes, it is.

**Comment by i-just** [comment]
Thanks! Is there any other info around the “Unknown command: ckeditor/convert”?

**Comment by jonathanbright** [comment]
Unfortunately, no. It's just the one line "Unknown command:
ckeditor/convert" and then the next line is the blank bash prompt.

**Comment by jonathanbright** [comment]
Also, this is on Craft 3 with PHP 7.4.

**Comment by i-just** [comment]
Ah, that clears it up then. 

The `ckeditor/convert` command is only available in CKEditor v3.1.0+ (available for Craft CMS 4.4.7+) and v4 (for Craft CMS 5). 

I’m not quite sure how you managed to install CKEditor 3.8.3 on Craft 3. As per the [original GH issue](https://github.com/craftcms/ckeditor/issues/200), if you want to use the command, you’ll have to update to at least Craft 4.4.7.

I hope this helps!
