### ISSUE TITLE
It is not possible to resize images and remove the set width and height values

### ISSUE THREAD

**Issue by jgpadua** [craftcms/ckeditor#273]
### Description
I'm not sure if this is a bug or something not implemented. But I would like to resize the images or at least remove the width and height values ​​that are added by default by CkEditor. This way I can't customize the aspect-ratio of the image to use what is defined in my style, since the values ​​are set inline in the source code.

I tried several customizations in the "Config options" but had no success.

### Additional info

- Craft version:  5.2.8
- PHP version: 8.3
- CkEditor: 4.1.0

**Comment by i-just** [comment]
Hi, thanks for reaching out! 

CKEditor [insists](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-overview.html#image-width-and-height-attributes) on keeping width and height attributes around.

You can resize your images via Asset Transforms. Here’s a related discussion that talks about image transforms: https://github.com/craftcms/ckeditor/discussions/94.

I hope this helps!
