### ISSUE TITLE
Word Count Regex Doesn't Recognize Single Opening Quote

### ISSUE THREAD

**Issue by tplassman** [craftcms/ckeditor#275]
### Description

When adding a maximum word count validation rule to the CKEditor field and then adding content to the field that contains a [single opening quote character](https://en.wikipedia.org/wiki/Right_single_quotation_mark) ( ‘ ) the `preg_matcha_all` call in the `getElementValidationRules` callback function breaks single words containing the single opening quote into two words instead of one.  The single opening quote character is also shown as being replace by the character `â€`.  This behavior is different from applying the same regex pattern (`(?:[\p{L}\p{N}]+\S?)+`) and test string to an [online regex testing](https://regex101.com/) tool that only matches a single word under the same conditions.

### Steps to reproduce

1. Create CKEditor field with a Word Limit validation rule set to 1.
2. Add a instance of this field to an entry type.
3. Add a single word containing a single opening quote character (e.g. we‘ve) to the field instance on an entry.

### Additional info

- Craft version: 4.10.7
- PHP version: 8.2.21
- Database driver & version: MySQL
- Plugins & versions: CKEditor 3.8.3

**Comment by i-just** [comment]
Hi, thanks for reporting and for the detailed description! I raised a PR for this.

**Comment by brandonkelly** [comment]
CKEditor 3.9.0 and 4.2.0 are out with that fix. Thanks again!
