### ISSUE TITLE
Add config attribute to field to help scope styles by assigned CKEditor configuration

### ISSUE THREAD

**Issue by webrgp** [craftcms/ckeditor#284]
I have a couple of CKEditor fields with different configurations. In order to be able to share common styles between editors while keeping the differences separated, it would be helpful if the field rendered a data attribute with the configuration in use, similar to `data-type="craft\fields\PlainText"`, using the CKEditor config name.

I the project I am working on it has a matrix field with a couple of different CKEditor fields that could use this.

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I raised a PR for this. You can find a bit more info in the PR’s description.

**Comment by brandonkelly** [comment]
CKEditor 3.10.0 and 4.3.0 are out with that new `data-config` attribute.
