### ISSUE TITLE
CKEditor toolbar display issue when using 'Show more items' button and dropdown icons

### ISSUE THREAD

**Issue by rogerdawkins** [craftcms/ckeditor#286]
### Description
If there are too many items to display in a CKEditor toolbar a vertical three dots 'Show more items' button is displayed. When the button is clicked another popout toolbar is displayed. If the popout toolbar contains any dropdown buttons such as Table, Bulleted List, New Entry, etc the layout fails when the user attempts to dropdown the list. The dropdown items are contained within the dimensions of the popout toolbar making the buttons unusable.

### Steps to reproduce

1. Create a CKEditor config with quite a few toolbar icons, including dropdown fields such as New Entry, Bulleted List, etc. Place a dropdown item towards the right hand end.
2. When entering data using the CKEditor field ensure the editor window is quite narrow so that the 'Show more icons' button is displayed.
3. Click the Show more icons button
4. Use any dropdown icon and you will see the issue

<img width="633" alt="Screenshot 2024-09-04 at 22 40 28" src="https://github.com/user-attachments/assets/2db7902f-6b6f-4f51-a387-cbb8981c1c44">

Image above shows the initial popout toolbar.

<img width="640" alt="Screenshot 2024-09-04 at 22 41 41" src="https://github.com/user-attachments/assets/03f5e2ad-e9e8-443c-a918-30556112d825">

Image above shows the display once a dropdown button is clicked. In this case the New Block button but it fails with all.

I tried the above on a Mac using Chrome, Firefox and Safari with similar results.

### Additional info

- Craft version: 5.4.1
- PHP version: 8.2.22
- Database driver & version: MySQL 8.0.36

- Plugins & versions:

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
CKEditor 3.10.0 and 4.3.0 are out with a fix for this. Thanks again!
