### ISSUE TITLE
php craft ckeditor/convert/redactor error 

### ISSUE THREAD

**Issue by brianhorace** [craftcms/ckeditor#288]
### Description

getting this error when I try to migrate to ckeditor:

php craft ckeditor/convert/redactor
PHP Deprecated:  auto_detect_line_endings is deprecated in /Users/testinfo/Documents/fiscalnote2/vendor/vlucas/phpdotenv/src/Loader.php on line 172

Deprecated: auto_detect_line_endings is deprecated in /Users/testinfo/Documents/fiscalnote2/vendor/vlucas/phpdotenv/src/Loader.php on line 172

    Craft can’t connect to the database. Check your connection settings.    

Unknown command: ckeditor/convert/redactor
Caused by: Exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "ckeditor/convert/redactor".'

in /Users/testinfo/Documents/fiscalnote2/vendor/yiisoft/yii2/base/Module.php:561

Stack trace:
#0 /Users/testinfo/Documents/fiscalnote2/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('ckeditor/conver...', Array)
#1 /Users/testinfo/Documents/fiscalnote2/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('ckeditor/conver...', Array)
#2 /Users/testinfo/Documents/fiscalnote2/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('ckeditor/conver...', Array)
#3 /Users/testinfo/Documents/fiscalnote2/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#4 /Users/testinfo/Documents/fiscalnote2/craft(22): yii\base\Application->run()
#5 {main}

### Steps to reproduce

1. just ran: php craft ckeditor/convert/redactor error 
2.

### Additional info

- Craft version: 3.7.37. 
- PHP version:  7.4.33
- Database driver & version:  MySQL 8.0.33
- Plugins & versions:

Plugins
Amazon S3	1.3.0
Asset Rev	6.0.2
CKEditor	1.4.0
Cloner	1.2.2
Colour Swatches	1.6.0
Control Panel CSS	2.4.0
Environment Label	3.2.0
Field Manager	2.2.5
Icon Picker	1.1.14
Navigation	1.4.33
Neo	2.13.19
Pickture	1.0.0
Redactor	2.10.9
Redirect Manager	1.1.1
SEOmatic	3.4.35
Servd Assets and Helpers	2.10.4
Simple Sharing	1.0.8
Spoon	3.7.0
Sprig	1.13.0
Super Table	2.7.2
Tags	1.0.9
Template Comments	1.2.0
Twig Perversion	2.2.0
Typed link field	1.0.25
Video Embed	1.2.2
Vite	1.0.30
Wheel Form	2.7.2
Wordsmith	3.3.2

**Comment by i-just** [comment]
Hi, thanks for getting in touch! The `ckeditor/convert` command was added in CKEditor 3.1.0, which requires Craft CMS 4.4.7 or higher. If you wish to use the command, you’ll have to update to at least those versions.
