### ISSUE TITLE
How to apply custom CSS to an editor?

### ISSUE THREAD

**Issue by proimage** [craftcms/ckeditor#29]
Based on what it says [here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html), I'm trying to apply custom styles to the editor (for a specific field). I have this line in the "Initialization Code" field for the CKEditor field in question:

```import '/assets/css/ckeditor.css';```

When I load that field (say, in an entry editing screen), CKEditor fails to initialize, and I get this console error:
```
VM4946:2 Uncaught SyntaxError: Cannot use import statement outside a module
    at m (jquery.js:133)
    at Oe (jquery.js:6114)
    at b.fn.init.append (jquery.js:6250)
    at s.constructor.initUi (main.js?v=1623931468:13)
    at s.constructor.addBlock (main.js?v=1623931468:13)
    at s.constructor.init (main.js?v=1623931468:12)
    at s.constructor.constructor (garnish.js:764)
    at s.constructor (garnish.js:40)
    at new s.constructor (garnish.js:40)
    at Object.createInput (main.js?v=1623931468:1)
```
I'm a humble HTML & CSS dev, and my JS is weaksauce. What am I doing wrong? And why is it so complicated? 😖

**Comment by grcodemonkey** [comment]
If you want to add a stylesheet to the authoring experience, you'll need to add it using javascript

```
(function() {
  if (window.ckStylesAdded) { return; }

  var head = document.head;
  var link = document.createElement("link");

  link.type = "text/css";
  link.rel = "stylesheet";
  link.href = '/assets/css/ckeditor.css';

  head.appendChild(link);

  window.ckStylesAdded = true;
})();
```

**Comment by brandonkelly** [comment]
Version 3.0 came out last week, with new globally-managed CKEditor configs. Each config can define CSS styles that should be registered for pages that include a CKEditor field using that config.

**Comment by brandonkelly** [comment]
Theoretically yes. It would be relative to the current URL in the control panel, so an absolute / root-relative URL is probably your best bet.
