### ISSUE TITLE
Paste-as-plaintext

### ISSUE THREAD

**Issue by jtschulik-pcweb** [craftcms/ckeditor#290]
### Description

The paste-as-plain-text (ctrl+shift+V)) functionality sadly doesn't work. I guess that's because the clipboard-feature (https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-clipboard) is not implemented.
Please implement this very important feature!

### Steps to reproduce

1. Copy some formatted text from e.g. word
2. ctrl+shift+V paste in the editor

### Additional info

- Craft version: 5.3.6
- PHP version: 8.2.23
- Database driver & version: MariaDB 10.11.9
- Plugins & versions: ckeditor 4.2.0

**Comment by lukew-cogapp** [comment]
@jtschulik-pcweb Did you ever figure out how to implement/enable CKEditor packages that aren't enabled in the plugin?

**Comment by jtschulik-pcweb** [comment]
@lukew-cogapp no, the above issue wasn't an issue but a user error ;)
