### ISSUE TITLE
Adding a decorator for links breaks unlink

### ISSUE THREAD

**Issue by kbergha** [craftcms/ckeditor#297]
### Description

Adding a decorator for links, the unlink feature breaks / causes console errors.

### Steps to reproduce

1. Configure CKE with the following config options:
![unlink-cke-config](https://github.com/user-attachments/assets/abb2d700-ff0f-4795-94e8-ceccb9597865)

Config options / Decorator code:
```
return {
  link: {
    decorators: {
      isPhoneShortNumber: {
        mode: 'automatic',
        callback: url => url.match(/[+47]?\d{5}/g),
          attributes: {
              'class': 'ET-phone-home'
          }
      },
    },
  },  
  list: {
    properties: {
      styles: false,
    },
  },
}
```
2. Add a link, in this case to `12345`, which matches the regex.
![unlink-decorator](https://github.com/user-attachments/assets/1882c462-fad4-43e3-a5ff-32a72e6c1862)

3. See that `ET-phone-home` is added to the anchor element.
![unlink-decorator-html](https://github.com/user-attachments/assets/457ea70c-2d8b-4cbf-975b-7d1e738d7ff9)

4. Try to unlink
![unlink-before-clicking](https://github.com/user-attachments/assets/70ca5b66-349f-4cd9-96f9-6788f3ae5f60)

5. Observe console error, "This link has no URL" and that "This is a link" still has link styling.
![unlink-console-error](https://github.com/user-attachments/assets/bef82234-2693-4241-916e-166a62677df2)

Console error:
```
Uncaught CKEditorError: Cannot read properties of null (reading 'match')
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-Cannot read properties of null (reading 'match')
    at Object.callback (240-bork-bork-bork:1254:30)
    at Zo.<anonymous> (automaticdecorators.js:73:30)
    at Zo.fire (ckeditor5-dll.js?v=1727165961:2:628930)
    at Zo._testAndFire (ckeditor5-dll.js?v=1727165961:2:284745)
    at Zo._convertAttribute (ckeditor5-dll.js?v=1727165961:2:283201)
    at Zo.convertChanges (ckeditor5-dll.js?v=1727165961:2:281329)
    at ckeditor5-dll.js?v=1727165961:2:319634
    at fo.change (ckeditor5-dll.js?v=1727165961:2:250056)
    at Cr.<anonymous> (ckeditor5-dll.js?v=1727165961:2:319598)
    at Cr.fire (ckeditor5-dll.js?v=1727165961:2:628930)
```

6. Clicking around creates more console errors. I've clicked the unordered list in this example, but the styling / HTML does not seem to be applied.
![unlink-multiple-console-errors](https://github.com/user-attachments/assets/4e11d1c8-bf76-4a15-bfdb-2e8d35b561d2)

7. Saving the entry, the unordered list HTML/styling from the previous step is applied.
![unlink-list](https://github.com/user-attachments/assets/d53ace77-2079-4da3-b10f-85bf0e1a225c)

### A note to step 2

It does not seem to matter if what you're linking to matches the decorator regex or not.
The error happens when linking and unlinking to `https://example.com` as well as long as the decorator is present.

### Expected behaviour

This is without the decorator.

1. Click unlink.
![unlink-no-decorator-before-unlink](https://github.com/user-attachments/assets/44cf0768-3dee-4c1b-8d76-09197b8c5dfd)

2. Only the previous link text is present. No "This link has no URL", and no link styling / console errors.
![unlink-no-decorator-after-unlink](https://github.com/user-attachments/assets/13d1ad39-6905-4bc1-90a9-314e5b27e4b5)

### Additional info

- Craft version: 5.4.6
- PHP version: 8.3.8
- Database driver & version: MySQL 8.0.34
- Plugins & versions: 
CKEditor 4.2.0
Amazon S3 2.2.1
Amazon SES 3.1.0
Blitz	5.7.1
Blitz CloudFront Purger 5.1.0
Vite 5.0.1

HTML Purifier config:
```
{
  "AutoFormat.Linkify": true,
  "AutoFormat.RemoveEmpty": true,
  "AutoFormat.RemoveEmpty.RemoveNbsp": true,
  "HTML.Allowed": "a[href|class],p,ul,ol,li,h2,h3,h4,h5"
}
```

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

This error comes from CKEditor itself. If you adjust the callback to account for the fact that the URL might be `null`, it should start working as expected. 
For example: `callback: url => url?.match(/[+47]?\d{5}/g),` or you can use this syntax from the [docs](https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-target-and-rel-attributes-to-external-links): `callback: url => /[+47]?\d{5}/g.test(url),`. 

I hope this helps!

I’ll close this now, but feel free to reach out if you run into any further issues.

**Comment by kbergha** [comment]
Thank you for the fast troubleshooting.
