### ISSUE TITLE
Live Preview editor mode not working

### ISSUE THREAD

**Issue by skramstad** [craftcms/ckeditor#3]
Hi.

When i add a new text block and typing some random text it does not show up in the preview window. Can't see any errors in the console.

If I then save the entry in Live Preview mode it says that the field is empty and I have to re-enter the text. My text block is required.

Craft CMS RC 8 and CKEditor 1.0.0-beta.2.

**Comment by tyler-shaw** [comment]
I'm also seeing an issue where changes in the CKEditor field are not reflected in the Live Preview.

**Comment by shaack** [comment]
Live Preview is not working for me with Craft CMS 3.1.25. CKEditor 1.0.0-beta.2.

**Comment by AlexanderSix** [comment]
I am currently experiencing the same issue. No errors to be found though.

**Comment by brandonkelly** [comment]
This should be fixed as of Craft 3.2 + and CKEditor 1.0.0-beta.3.
