### ISSUE TITLE
Option to link to Categories / Assets

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/ckeditor#302]
### Description
Not sure if I'm just not looking in the right area, but is there any way to add the option to link to cateogires / assets? Currently the only options in my Link dropdown is 'Link to an entry' and 'Insert link'. 

### Additional info

- Craft version: 5.4.7.1
- PHP version: 8.2.15
- Plugins & versions: 4.2.0

**Comment by i-just** [comment]
Hi, thanks for reaching out! 

The option to link to categories will show if you set up at least one category group in the Control Panel.
For the option to link to assets to show, you need to have at least one volume set up, and the CKEditor field needs to have at least that one volume selected.

I hope this helps!

I’ll close this now, but feel free to reply if you run into any further issues.

**Comment by iamtompickering** [comment]
Hi @i-just thanks for this! But I actually have 3 category groups already set up in the admin and the category option still isn't showing under the Link dropdown.

**Comment by i-just** [comment]
Thanks for confirming! Do all those groups have URLs (Category URI Format is not empty) on the site you’re editing?

**Comment by iamtompickering** [comment]
@i-just ahh yes sorry that will be why! Thanks for that!

**Comment by i-just** [comment]
Not a problem. Glad it’s working as expected!

**Comment by sweetroll** [comment]
Hi @i-just is there a way to have the the asset card show in the editor rather than just a link?

**Comment by i-just** [comment]
Not via the Link option, no. What you could do is create an entry type with an Assets field in it (you could also set that field to be used for element thumbnails or to show in the card view), ensure your CKEditor field allows that entry type and that the config used by it has “New entry” item added. Then, you could start adding assets within those nested entries, and those nested entries would show as cards. It’s not the same as linking to an asset, but maybe it’ll suit your needs.

**Comment by sweetroll** [comment]
@i-just couldn't get the related assets displaying in the card style in the editor using the above. All good. I've seen improvements with each update so pretty confident I'll get added in the future. Cheers.
