### ISSUE TITLE
Classname overwritte with Craft cms

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/ckeditor#303]
### Description

Hello, if i use the same classname of one of Craft CMS classname, the style is apply.
If i declare a classname used by Craft, Craft element is overwritted.

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/486f532a-4936-4713-b85a-ca2307427e0b)

Will change all the Craft cms button style

![Image](https://github.com/user-attachments/assets/81a36537-42a7-4148-b505-4473150df3b2)

-----

![Image](https://github.com/user-attachments/assets/1499b993-186a-47e2-8ffc-4fd68a25b5e9)

Will change the btn style in my Cke Editor

![Image](https://github.com/user-attachments/assets/cfdd6a3d-6de0-43e8-b701-5b65d628c205)

### Additional info

- Craft version: 5.4.7.1
- Plugins & versions: 4.2.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

The styles you define in the CKEditor Config Custom Styles field are added to the head of the page (and apply to the whole page). If you use a class name that’s used in other places, those styles will affect elements outside of the CKEditor, too. If that's not a desired behaviour in your case, you can either use a unique class name (e.g. `mycke-btn`), or ensure your styles only target that class name when it’s inside a CKEditor field (e.g. `.ck-editor__main .btn`).

I hope this helps!

I’ll close this now, but feel free to reach out again if you run into any further problems.
