### ISSUE TITLE
HTML Purifier EnableID doesn't work

### ISSUE THREAD

**Issue by handplant** [craftcms/ckeditor#304]
Hello, I would like to allow IDs in Richtext. However, they are being stripped when saving.

Here is my config:

```
{
  "Attr.AllowedFrameTargets": [
    "_blank"
  ],
  "Attr.EnableID": true,
  "HTML.AllowedComments": [
    "pagebreak"
  ],
  "HTML.SafeIframe": true,
  "URI.SafeIframeRegexp": "%^(https?:)?//(www.youtube.com/|player.vimeo.com/)%"
}
```

Here my field:
![Image](https://github.com/user-attachments/assets/1614edd3-75f6-4cb4-a44a-b289cad804dc)

Thanks in advance!

### Additional info

- Craft version: Craft Pro 5.4.7.1
- PHP version: 8.2.21
- Plugins & versions: CKEditor | 4.2.0

**Comment by i-just** [comment]
Hi, thanks for reaching out!

Custom attributes and classes are stripped out (by default) by CKEditor itself. In addition to configuring your HTML Purifier, you also have to configure the CKEditor to allow IDs.

For example, this snippet allows for IDs for paragraph tags only:
```
return {
  htmlSupport: {
    allow: [
      {
        attributes: [
          'id',
        ],
        name: 'p',
      },
    ],
  },
}
```

You can find more info on CKEditor and HTML Purifier configuration [here](https://github.com/craftcms/ckeditor/issues/217).

I hope this helps!

I’ll close this now, but feel free to reach out again if you run into any further problems.

**Comment by handplant** [comment]
@i-just I’ve disabled the HTML Purifier for a specific field and tried the following CKEditor configurations:

```
return {
	htmlSupport: {
		allow: [
			{
				name: /.*/,
				attributes: true,
				classes: true,
				styles: true
			},
			{
				attributes: ['id'],
				name: 'a',
			},
		]
	},
}
```

Unfortunately, when I add HTML through the “Source” mode, the id attributes on links are still being **stripped out**. I need to preserve these id attributes on the anchor (<a>) tags like this:

```
<sup>
   <a id="fnref_1" href="#footnote_1">1</a>
</sup>
<div>
   <sup id="footnote_1">1</sup>
   <a href="#fnref_1">back</a>
</div>
```

Thx

**Comment by handplant** [comment]
It seems to be a bug related to the handling of id attributes on anchor (<a>) tags. When I paste the following code into the “Source” mode and save the content, the id attribute is preserved in the frontend:
```
<a id="fnref_1" href="#footnote_1">1</a>
```

However, when I edit or update the content in the field (manually, not in “Source” mode) and save again, the id attribute on the anchor tag is stripped out.


```
<a href="#footnote_1">1</a>
```

**Comment by i-just** [comment]
I tested your CKEditor configuration (with HTML Purifier disabled), and it does preserve the ID attribute on the A tag (and on the SUP tag too). Can you double-check that the field you’re testing this on uses the CKEditor configuration you adjusted?

https://github.com/user-attachments/assets/89cf49a0-64f9-41d8-860f-b6ce2a438ea3


That said, you now have two rules in there: one that allows any styles, attributes and classes on all elements and the other that only allows an ID attribute on A tags, so one of them seems redundant, depending on the full solution you want to achieve.

Let me know if I missed your point!

**Comment by handplant** [comment]
Thank you for your response. It’s very strange. Here’s my video showing the same process.

https://github.com/user-attachments/assets/98cbe1ee-0534-497f-93eb-f4dfc6354e67

**Comment by handplant** [comment]
@i-just Okay, I think I found the problem. It’s caused by the Anchor plugin! When I remove it, everything works as expected.

![Image](https://github.com/user-attachments/assets/1872286a-e98b-4e8e-8992-eca942196f4c)
