### ISSUE TITLE
No initialisation when used in a matrix

### ISSUE THREAD

**Issue by bartrylant** [craftcms/ckeditor#31]
### Description
I have a CKeditor field inside a matrix. When I make a new entry, and add the block with the CKeditor field inside, it just shows an unstyled textarea, there is no initialisation. It does work fine when the entry gets saved and reloaded.

### Additional info
- Craft version: 3.7 beta 2
- PHP version: 7.4

**Comment by nicbou** [comment]
I do not have this issue in the latest non-beta version. The editor shows, although the config options don't seem to have an effect.
