### ISSUE TITLE
Question: Automatically add nofollow based on a link url pattern?

### ISSUE THREAD

**Issue by tibbis** [craftcms/ckeditor#321]
### Description
Is it possible to using the htmlpurifier/ckeditor 5 config to automatically add `rel="nofollow"` based on a link's url pattern?

### Additional info

- Craft version: 5.5

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Sure, have a look at: https://ckeditor.com/docs/ckeditor5/latest/features/link.html#custom-link-attributes-decorators. You’ll need to add the configuration you’re after in the control panel > Settings > CKEditor > selected configuration > Config Options field. 

You’ll also have to make sure that the rel attribute with this value is allowed by the HTML Purifier config. For example:
```
"Attr.AllowedRel": [
    "nofollow",
    "noopener",
    "noreferrer"
],
```

I’ll close this now, but feel free to reply if you run into any problems.
