### ISSUE TITLE
RTL language support

### ISSUE THREAD

**Issue by maries24** [craftcms/ckeditor#33]
When editing content in Arabic (right-to-left language), the instances of CKEditor are still the left-to-right (and not RTL). 
Please note these CKEditor inputs are part of a matrix field. I haven't tested it as a standalone field.

The entry title field is rtl, which means the page reading direction is set correctly.

The div that wraps the CKEditor input wrapping has the following value for the class attribute: "input rtl".

CKEditor require the class "cke_rtl" (as opposed to "rtl") to switch to RTL mode (see https://ckeditor.com/docs/ckeditor4/latest/guide/skin_sdk_rtl.html) That might be the way to fix the issue.

Thanks!

**Comment by brandonkelly** [comment]
CKEditor 1.4.0 (Craft 3) and 2.1.0 (Craft 4) are out now with RTL support.
