### ISSUE TITLE
Open in new tab setting not preserved

### ISSUE THREAD

**Issue by palomamtnez** [craftcms/ckeditor#330]
### Description

I’ve updated my plugin configuration to enable links to open in new tabs by adding the following setting:

```return {
  alignment: {
    options: ['left', 'right', 'center', 'justify'],
  },
  code: {
    indentSequence: '  ',
  },
  link: {
    decorators: {
      openInNewTab: {
        mode: 'manual',
        label: 'Open in new tab?',
        attributes: {
          target: '_blank',
          rel: 'noopener noreferrer',
        },
      },
    },
  },
};
```

The "Open in new tab" toggle is now displayed as expected. However, when I enable the toggle and save the link, the setting is not preserved. Upon inspecting the saved link, the "Open in new tab" toggle is visible but remains turned off, as if the change wasn’t saved.

Could someone help me troubleshoot this issue?

### Additional info

- Craft version: 5.4.3
- PHP version: 8.3.13
- Database driver & version:  MySQL 8.0.35
- Plugins & versions:
    "craftcms/ckeditor": "4.2.0",
    "craftcms/cms": "5.4.3",
    "craftpulse/craft-colour-swatches": "5.0.2",
    "nystudio107/craft-seomatic": "5.1.3",
    "spicyweb/craft-embedded-assets": "5.1.2",
    "spicyweb/craft-neo": "5.2.5",
    "verbb/hyper": "2.0.5",
    "verbb/navigation": "3.0.4",
    "vlucas/phpdotenv": "^5.4.0"

**Comment by i-just** [comment]
Hi, thanks for getting in touch! It sounds like your HTML Purifier config needs some adjusting. Check which config file is used by the CKEditor field you're seeing this behaviour in (Settings > Fields > your field > Advanced).

To allow `target="_blank"`, you need:
```
"Attr.AllowedFrameTargets": [
    "_blank"
],
```
To allow the `rel` attribute with the values you specified in your CKEditor Config, you need:
```
"Attr.AllowedRel": [
    "noopener",
    "noreferrer"
],
```

I hope this helps! 

I'll close this now, but feel free to reply if you run into any further issues.
