### ISSUE TITLE
Changes made in source mode not saved

### ISSUE THREAD

**Issue by jean-gui** [craftcms/ckeditor#34]
### Description

If we make changes to a ckeditor field in source mode and immediately save the entry, those changes are not taken into account.
For changes to be taken into account it's necessary to switch back to WYSIWYG and then save.

### Steps to reproduce

1. edit or create an entry
2. switch a ckeditor field to source mode
3. make changes to the field
4. save

=> Changes are lost

### Additional info

- Craft version: 3.7.24
- PHP version: 7.4.26
- Database driver & version:
- Plugins & versions: craftcms/ckeditor 1.1.2

I've made a small video showing the behaviour:

https://user-images.githubusercontent.com/1479073/145244737-8e373f46-e990-441e-95cc-f013f19b5f0d.mp4

**Comment by i-just** [comment]
Hi, thanks for reporting and for the video! I’ve created a PR to fix this.

**Comment by brandonkelly** [comment]
CKEditor 1.5.0 (Craft 3) and 2.2.0 (Craft 4) are out now with the fix for this. Thanks again!
