### ISSUE TITLE
BaseUrl changed: Incorrect url loaded in script tag

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [craftcms/ckeditor#35]
### Description
I've tried the following urls in settings but unable to load them correctly:

http://@web/js/ckeditor5-31.1.0/src/ckeditor.js
http://$DEFAULT_SITE_URL/js/ckeditor5-31.1.0/src/ckeditor.js

### Steps to reproduce

1. Set baseurl to one of the values above and save (everything is validated and saves ok)
2. load a CKeditor instance
3. the js file loaded will have an incorrect path

    - http://$default_site_url/js/ckeditor5-31.1.0/src/ckeditor.js
    - http://web/js/ckeditor5-31.1.0/src/ckeditor.js

### Additional info

- Craft version: 3.7.23
- PHP version: 8.0
- Database driver & version:
- Plugins & versions: CKEDITOR latest

<img width="578" alt="Captura de pantalla 2021-12-14 a las 20 44 01" src="https://user-images.githubusercontent.com/90317987/146068541-a03e7d39-7473-44c4-9041-32fb37561054.png">
<img width="888" alt="Captura de pantalla 2021-12-14 a las 20 43 43" src="https://user-images.githubusercontent.com/90317987/146068548-dd4f4384-0891-405c-95a4-b52f14bc968c.png">

**Comment by eduardoalonsoalbella** [comment]
Ok, found how to fix the baseUrl problem:

Changed the path to: /js/ckeditor5-31.1.0/src/ckeditor.js

**Comment by Mosnar** [comment]
@eduardoalonsoalbella for future reference, environment variables can only be used to replace the entire field - you can't insert it into the middle of a text input like in your screenshot. You can **however** prepend aliases - see docs: https://craftcms.com/docs/3.x/config/#aliases

I would add an alias your general.php config for your default site URL:
```
"@defaultSiteUrl" => \App::env('$DEFAULT_SITE_URL')
```

and then in your config, you should be able to use: 
`@defaultSiteUrl/js/ckeditor5-31.1.0/src/ckeditor.js`

Note, the alias has to be in the beginning, so your DEFAULT_SITE_URL should include the `https://`

**Comment by eduardoalonsoalbella** [comment]
Thanks for the info!

In the end, I did a new module and loaded an external js file
