### ISSUE TITLE
Composer installation gives InvalidArgumentException

### ISSUE THREAD

**Issue by TheRuky** [craftcms/ckeditor#4]
I am currently running `Craft CMS 3.0.0-RC13`.

When I try to install `ckeditor` using `composer require craftcms/ckeditor`, I get:

```
 [InvalidArgumentException]
  Could not find a version of package craftcms/ckeditor matching your minimum-stability (stable). Require it with an ex
  plicit version constraint allowing its desired stability.
```
My Composer version is `1.6.3`.

However, using `composer require craftcms/ckeditor:1.0.0-beta.2` works.

**Comment by jeremyfrank** [comment]
I am running into the same issue with Craft CMS 3.0.0-RC15 and the same version of composer.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, any plan for a stable release on this?

**Comment by brandonkelly** [comment]
CKEditor 1.0.0 (stable) is out now, which resolves this error.
