### ISSUE TITLE
Not able to add image assets

### ISSUE THREAD

**Issue by baldhadhaval08** [craftcms/ckeditor#45]
### Description

Hello,

I'm getting error when trying to upload image. It's showing empty dialog when clicking on "Browser the server" button.
![image](https://user-images.githubusercontent.com/36040948/193398686-c9cc285a-be3b-43fb-984e-9c47d66ff2ca.png)

I'm using creditor 4.9.1https://cdn.ckeditor.com/4.9.1/full/ckeditor.js

### Steps to reproduce

1. Create a field with Field type ckeditor 
![image](https://user-images.githubusercontent.com/36040948/193398971-871496a8-2cc9-4ea6-bdba-0ad3d9940e3a.png)
2. Go in entries and click on image upload icon in CKEditor
3. Click on Browser the server button. 

### Additional info

- Craft version: 4.0.0.1
- PHP version: 8.0
- Database driver & version: mysql 8.0.23 
- Plugins & versions: craftcms/ckeditor : ^2.0

**Comment by brandonkelly** [comment]
Thanks for reporting! 2.1.0 is out with a fix for this.
