### ISSUE TITLE
Empty field outputs <p>&nbsp;</p>

### ISSUE THREAD

**Issue by CreateSean** [craftcms/ckeditor#5]
ckeditor 1.0.0-beta.2
craft 3.0.1

I'm using the ckeditor and found this bug when setting a conditional to only display content if the field contains data.

```
      {% if entry.overview|length %}
        <h2>Asset Overview</h2>
        <div class="overview">
          {{ entry.overview }}
        </div><!-- /.overview -->
      {% endif %}
```

On the front end I expect nothing to display, but that doens't happen because ckeditor is outputting this

`<p>&nbsp;</p>`

Please advise

**Comment by lindseydiloreto** [comment]
Hi @Radabaugh,

Do you know when this fix will be pushed live?

I'm having the same problem

**Comment by Radabaugh** [comment]
Hey @lindseydiloreto, 

I'm still waiting on a code review of my pull request before it can be merged and pushed to live, I'll ping someone about it to try and speed things along.

**Comment by lindseydiloreto** [comment]
Great, thanks Tyler! I look forward to seeing this fix pushed live. 👍
