### ISSUE TITLE
Video Embeds Stripped Out Regardless of HTML Purifier Config

### ISSUE THREAD

**Issue by itsmattsoria** [craftcms/ckeditor#59]
### Description

The `Default.json` config for HTML Purifier that is included on installation has the following lines, which should prevent YouTube and Vimeo video embeds from being stripped out of a CKEditor field on save, but embeds from either platform are still being stripped out.

```json
  "HTML.SafeIframe": true,
  "URI.SafeIframeRegexp": "%^(https?:)?//(www.youtube.com/embed/|player.vimeo.com/video/)%"
```
I wasn't totally sure if this issue belongs here, or in the Craft starter, or with HTML Purifier itself, but for reference, I tested this with Redactor, and it wasn't an issue there, the embeds remained after save.

### Steps to reproduce

1. Do a fresh Craft install using the [Quick Start Guide](https://craftcms.com/docs/4.x/installation.html#quick-start)
2. Install the latest version of CKEditor with `ddev composer require craftcms/ckeditor -w && ddev exec php craft plugin/install ckeditor`
3. Keep the default installation settings, which at the time of writing includes `https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js` as the CKEditor Build URL.
4. Create a CKEditor field and add it to a section for use (you'll need to create a new section if starting fresh). Keep the default settings, which leaves "Purify HTML" as checked, and uses the `Default` config.
5. Go to the entry where the field was added, and paste in a YouTube or Vimeo URL ( I recommend [this one](https://www.youtube.com/watch?v=qkMmgqinuqs&ab_channel=MrBean)). The editor should automatically take that and produce the iframe code that displays it as an embed within the editor.
6. Hit "save" on the entry and see your empty field where the embed should remain.

### Additional info

- Craft version: 4.3.8.1 Solo
- PHP version: 8.0.24
- Database driver & version: MySQL 10.4.26
- Plugins & versions: Just CKEditor 2.2.0

**Comment by itsmattsoria** [comment]
@i-just Ahh, yep. Dang. Well thank you for that update, I appreciate it!

**Comment by brandonkelly** [comment]
Craft 3.7.66 and 4.3.9 are out with an update to the HTML Purifier config to allow `oembed` tags (via craftcms/cms#12675). There’s also a new [Embedding Videos/Media in CKEditor 5](https://github.com/craftcms/ckeditor#embedding-videosmedia-in-ckeditor-5) section in the plugin readme.

**Comment by FrDH** [comment]
We're on Craft 4.5.5 but YouTube video's are always stripped out when using HTML purifier, regardless of what config is used.

**Comment by kevinmu17** [comment]
4.5.9 also not working unless uncheck the Purify HTML option in the field.
