### ISSUE TITLE
Wrong headings

### ISSUE THREAD

**Issue by alexkuzmin** [craftcms/ckeditor#60]
### Description

CKEditor places wrong heading. E.g. h2 is chosen, h3 is placed.

### Steps to reproduce

1. Write some text, choose "Heading 2" option for it.
2. Check generated code - it is in tag <h3>.

### Additional info

- Craft version: 4.3.8.2
- PHP version: 8.0.8
- Database driver & version: MySQL 5.7.34
- Plugins & versions: CKEditor 2.2.0

<img width="432" alt="Screenshot 2023-02-09 at 12 12 54" src="https://user-images.githubusercontent.com/3720262/217798065-dc5499a1-4ee7-43d0-8410-f5c519528d28.png">

<img width="1358" alt="Screenshot 2023-02-09 at 12 20 03" src="https://user-images.githubusercontent.com/3720262/217798872-8e2ea8ad-bdeb-4e39-9205-783c3e944bce.png">

**Comment by i-just** [comment]
Hi, thanks for getting in touch. It looks like this is the default behaviour coming from CKEditor v5: https://github.com/ckeditor/ckeditor5/blob/dff5e8cd5432c67efab052d30f02fb6c6b37ffcb/packages/ckeditor5-heading/_src/heading.js#L52-L81

You can change it by adding your custom configuration in the field settings under `Initialization Code`. The following snippet would change the default behaviour to map `Heading 1` to `h1`, `Heading 2` to `h2` etc and would add `Heading 4` to the list:
```
return await ClassicEditor
    .create(document.querySelector('#__EDITOR__'), {
        heading: {
            options: [
               { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
               { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
               { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
               { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
               { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' }
           ]
       }
    });
```

This is a good starting point if you’re looking for ways to customise your editor: https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start.html#sample-implementation-2
