### ISSUE TITLE
CKEditor 5 beta 2

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/ckeditor#7]
Looks like CKEditor 5 is finally reaching some significant stability. Was curious what the going thoughts are on a roadmap for Craft integration. Thanks!

[CKEditor 5 v1.0.0 beta released](https://ckeditor.com/blog/CKEditor-5-v1.0.0-beta-released/#whats-next)

> We consider the API to be quite stable now and we do not expect any significant API changes at this stage. Feel free to fully try out CKEditor 5’s potential and update your code to align with the recent API changes.

**Comment by brandonkelly** [comment]
1.0.0 is out now, which uses CKEditor 5 (27.0.0) by default, and allows you to customize which build to use.
