### ISSUE TITLE
Lists are missing padding when viewing in the editor

### ISSUE THREAD

**Issue by mikejpeters** [craftcms/ckeditor#72]
### Description

Lists in CKEditor are missing padding. It seems like Tailwind reset is removing the margin and padding from all `ul` and `ol` elements in the control panel. (I'm assuming this CSS is being loaded by Craft itself but please let me know if I should be looking into my other plugins instead)

![image](https://user-images.githubusercontent.com/3334654/232623529-a7dd9655-e61d-49e5-bf9a-41a135199a4c.png)

### Steps to reproduce

1. Create a CKEditor field that includes a list button in the toolbar
2. Enter list items in the field

### Additional info

- Craft version: 4.4.7.1
- PHP version: 8.0.28
- Database driver & version: MySQL 8.0.31
- Plugins & versions:
  - Amazon S3	2.0.3
  - CKEditor	3.1.0
  - Google UA and GTM	2.1.3
  - Mailgun	3.0.0
  - Position Fieldtype	4.0.0
  - Sentry Logger	4.1.2
  - SEO	4.1.0
  - Super Table	3.0.8.1
  - Typogrify	4.0.1

**Comment by mikesnoeren** [comment]
I am seeing this too.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released CKEditor 3.2.0 with a fix.
