### ISSUE TITLE
Settings not saved to the database when adding config for 'target="_blank"' to link

### ISSUE THREAD

**Issue by kennethdenhollander** [craftcms/ckeditor#79]
### Description
In the Craft CMS CKEditor plugin I added some extra configuration so that a link can open in a new window. Instead of a configuration where an absolute URL always is opening in a new tab. 

### Steps to reproduce

1. Install the plugin
2. Modify the config with the code below
3. Try and make a link in a CK Editor field with the button 'open in new tab' enabled. After saving the entry the button is reset and not saved to the database

**Config**
`"link": {
    "decorators": {
      "openInNewTab": {
        "label": "Open in a new tab",
        "mode": "manual"
      }
    }
  }`

### Additional info

- Craft version: 4.4.7
- PHP version: 8.1
- Database driver & version: 10.5.9-MariaDB
- Plugins & versions: 3.1.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Based on the third code snippet here: https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-target-and-rel-attributes-to-external-links, it looks like your configuration is missing the `"attributes"` part. If you change your config to:
```
"link": {
    "decorators": {
      "openInNewTab": {
        "attributes": {
          "target": "_blank"
        },
        "label": "Open in a new tab",
        "mode": "manual"
      }
    }
  }
```
It should start working as expected.

Hope this helps!

**Comment by i-just** [comment]
@remcoov, you might need to tweak your HTML Purifier config. 
In order to support `_target="blank"` you need:
```
"Attr.AllowedFrameTargets": [
  "_blank"
],
```
and in order to support `rel="noopener noreferrer"`, you can use this:
```
"Attr.AllowedRel": [
  "noopener",
  "noreferrer"
],
```

**Comment by remcoov** [comment]
Hi @i-just, thanks for the quick answer.

```
"Attr.AllowedFrameTargets": [
  "_blank"
],
```

Is already in my config, so at least the _blank should stay where it is, but it is deleted.

**Comment by remcoov** [comment]
Ok, so when I added the:

```
"Attr.AllowedRel": [
  "noopener",
  "noreferrer"
],
```

it works! :-)

But that shouldn't be default behaviour, methinks? It should strip noopener and noreferrer, not target=_blank, since this is allowed in the config.

Thanks!

**Comment by CreateSean** [comment]
I'm having the same issue but do not know where to place the above code snippets. Honestly Redactor was simpler to use and the only reason I'm using CKeditor is because redactor is getting phased out afaik.

Here is my current config - where do I add the new lines to get the open in new tab to work correctly.

```
{
  "code": {
    "indentSequence": "  "
  },
  "link": {
    "addTargetToExternalLinks": false,
    "decorators": {
      "openInNewTab": {
        "attributes": {
          "rel": "noopener noreferrer",
          "target": "_blank"
        },
        "label": "Open in a new tab",
        "mode": "manual"
      }
    }
  },
  "style": {
    // more code here
  }
}
````

**Comment by brandonkelly** [comment]
> But that shouldn't be default behaviour, methinks? It should strip noopener and noreferrer, not target=_blank, since this is allowed in the config.

Agreed! Just made that the case for the next release (a80313136ad2c702464ac25051ff31026d5619f7).

> where do I add the new lines to get the open in new tab to work correctly.

@CreateSean In the HTML Purifier config selected by your CKEditor field (`config/htmlpurifier/...`). But at this point, just wait for the next release and you won’t have to worry about it.

**Comment by brandonkelly** [comment]
CKEditor 3.5.0 is out with support for automatically allowing `noopener`, `noreferrer` and `target="_blank"`. :tada:

Note that the update requires [Craft 4.5.0](https://craftcms.com/blog/craft-4-5-released).
