### ISSUE TITLE
Headings are wrong

### ISSUE THREAD

**Issue by thaoms** [craftcms/ckeditor#8]
Selecting h1 gives you a h2 in the source
h2 -> h3 

and so on.

**Comment by mightyfineyall** [comment]
Same issue here. Was going to use this rich text editor because Redactor doesn't show which heading the current text is formatted as, but ckeditor gets the headings wrong anyways. Plus zero config options. Back to Redactor I guess - doesn't look like Pixel and Tonic wants to mess with this anymore.

**Comment by brandonkelly** [comment]
This is expected (see [Headings](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html) in the CKEditor 5 docs).

We’ve just released version 1.0.0 of the plugin, which allows you to [customize the editor configuration](https://github.com/craftcms/ckeditor#editor-configuration), so you can change this if needed.
