### ISSUE TITLE
Table rows and columns can not be added after creation

### ISSUE THREAD

**Issue by eddiedale** [craftcms/ckeditor#81]
### Description
Adding a table works as expected, but if you thereafter want to add a column or row that is not possible.

It can be solved by this added to the config:
```
return {
  table: {
      contentToolbar: [ 'tableColumn', 'tableRow', 'mergeTableCells' ]
  }
}
```

These options do however seem very sensible to enable by default.

### Additional info

- Craft version: Craft Pro 4.4.7.1
- PHP version: 8.2.0
- Database driver & version: MariaDB 10.4.27
- CKEditor versions: 3.2.0

**Comment by brandonkelly** [comment]
Thanks for pointing that out! We just tagged 3.3.0 which includes a table toolbar, with row, column, and cell-merging controls.
