### ISSUE TITLE
Feature Request: Add option to hide source button from non-admins like Redactor has

### ISSUE THREAD

**Issue by CreateSean** [craftcms/ckeditor#82]
### Description

Want to have the option to include the source button but make it available only to Admins or specific user groups. See screenshot from redactor config.

![image](https://user-images.githubusercontent.com/6899490/233669031-98385b52-5c5c-42a3-a82f-3e5d47007a43.png)

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 4.4.7
- PHP version:
- Database driver & version:
- Plugins & version: CKEditor  3.2.0

**Comment by brandonkelly** [comment]
Added for the next release! (via #87)

**Comment by kevinmu17** [comment]
Yesterday I was so pleased this feature was not implemented in CKeditor due to extensive switching this on for every text field. Can't this be an opt-in feature? **Hide for non admin users**?

**Comment by brandonkelly** [comment]
@kevinmu17 I opted for consistency with Redactor.

You can swap all current fields’ settings by doing the following:

1. Run `php craft project-config/rebuild`
2. Find/replace `enableSourceEditingForNonAdmins: false` with `enableSourceEditingForNonAdmins: true` in your `config/project` folder
Run `php craft project-config/apply`

**Comment by kevinmu17** [comment]
Hero of me man!
