### ISSUE TITLE
[4.x]: When a CKEditor field contains  a `<br>` tag it gets marked as changed on focus

### ISSUE THREAD

**Issue by thupsi** [craftcms/ckeditor#85]
### Description
When a CKEditor field contains  a `<br>` tag it gets marked as changed on focus.

### Steps to reproduce

1. Create a CKEditor field and add it to an entry type.
2. Go to an entry and type some text in the field, including a `<br>` tag (eg  with `SHIFT + ENTER`).
3. Save the entry.
4. Click in the field, withour typing anything.

### Expected behavior

The field should not get marked as changed until the editor actually types something.

### Actual behavior

The field gets marked as changed.

### Craft CMS version

Craft CMS 4.4.7.1

### Installed plugins and versions

CKEditor	3.2.0

**Comment by brandonkelly** [comment]
Fixed for the next release via #83!

**Comment by i-just** [comment]
> Should I open a separate issue?

Yes, please!

**Comment by brandonkelly** [comment]
3.3.0 is out with that fix 🎉
