### ISSUE TITLE
shift  + enter doesn't add break

### ISSUE THREAD

**Issue by thaoms** [craftcms/ckeditor#9]
When using shift + enter we don't get a single line-break but a new p tag.

**Comment by theskyfloor** [comment]
This is an ongoing discussion for CKEditor in its core implementation. Looks like they will be adding it at some point:

https://github.com/ckeditor/ckeditor5-enter/issues/2

**Comment by theskyfloor** [comment]
Looks like the latest dev builds of CKEditor have this included now!

**Comment by brandonkelly** [comment]
We just released version 1.0.0 of the plugin, which uses CKEditor 5 (27.0.0) by default, and can confirm this works as expected now.
