### ISSUE TITLE
Fields with links and `&nbsp;` get marked as modified on focus.

### ISSUE THREAD

**Issue by thupsi** [craftcms/ckeditor#90]
### Description
See https://github.com/craftcms/ckeditor/issues/85

### Steps to reproduce

1. Create a CKEditor field and add it to an entry type.
2. Go to an entry and add a link or a `&nbsp;` entity (eg by hitting ENTER twice, which creates an empty paragraph).
3. Save the entry.
4. Click in the field, withour typing anything.
5. The field appears dirty.

### Additional info

- Craft version: 4.4.8
- PHP version:
- Database driver & version:
- Plugins & versions: CKEditor 3.2.1

**Comment by brandonkelly** [comment]
Fixed for the next release! Thanks for reporting.

**Comment by brandonkelly** [comment]
3.3.0 is out with that fix 🎉

**Comment by thupsi** [comment]
@brandonkelly This issue has been reintroduced, this time only for links (as far as I can tell). I'm on Craft 4.4.13.

**Comment by brandonkelly** [comment]
Able to reproduce with links with `rel` attributes. HTML Purifier is moving that attribute to the end of the `<a>` tag, causing CKEditor to want to re-normalize it back to before the `href` attribute, which makes Craft think the field value has changed.

We’ll see what we can do to work around that…

**Comment by brandonkelly** [comment]
Just realized there’s an easy solution to this: have the editor spit out its normalized value immediately on initialization, before Craft has captured the initial form values for change tracking. So this is now really fixed for the next release.

**Comment by brandonkelly** [comment]
CKEditor 3.5.0 is out with this fix :tada:

Note that the update requires [Craft 4.5.0](https://craftcms.com/blog/craft-4-5-released).
