### ISSUE TITLE
Crashes upon saving with view source open

### ISSUE THREAD

**Issue by morris76** [craftcms/ckeditor#95]
### Description
If I select the source code option and then try to save the entry (with the source code open), the browser crashes.

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by i-just** [comment]
Hi, thanks for reaching out. Could you please provide the Craft version, PHP version and at least the CKEditor plugin version? Also, which browser is this happening in?
