### ISSUE TITLE
CKEditor config addTargetToExternalLinks doesn't look for internal links.

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/ckeditor#98]
### Description

When adding this option the expected behaviour would be that only external links get the `target="blank"` attribute, however, all links get it.

Config:
```js
return {
  link: {
    addTargetToExternalLinks: true,
  },
}
```

Workaround is to set targets manually, using this config:
```js
return {
  "link": {
    "decorators": {
      "openInNewTab": {
        "attributes": {
          "target": "_blank"
        },
        "label": "Open in a new tab",
        "mode": "manual"
      }
    }
  }
}
```

**Comment by lukas-jansen** [comment]
https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-target-and-rel-attributes-to-external-links looks to be the expected behavior for CkEditor but it is confusing that links to entries are now also getting it. 
Maybe it shouldn't be set as a default config option?

**Comment by brandonkelly** [comment]
Gross, I didn’t realize how loosely it labels links as “external”. The `ckeditor/convert` command won’t set `link.addTargetToExternalLinks = true` anymore going forward.

**Comment by remcoov** [comment]
@brandonkelly Internal links are still being treated as external links, in new CKEditor fields..

**Comment by kevinmu17** [comment]
When using the decorator within the link option and you are using the `rel` attribute, you need to update your htmlpurifier config with this:

### CKeditor config option (within the Craft CMS cp)
```js
{
  "link": {
    "addTargetToExternalLinks": false,
    "decorators": {
      "openInNewTab": {
        "attributes": {
          "rel": "noopener noreferrer",
          "target": "_blank"
        },
        "label": "Open in a new tab",
        "mode": "manual"
      }
    }
  }
}
```
### htmlpurifier config (.json)
```js
{
  "Attr.AllowedFrameTargets": [
    "_blank"
  ],
  "Attr.AllowedRel": [
    "noopener",
    "noreferrer"
  ]
}
```

Maybe this can be implemented as a default @brandonkelly ? since the rel option to externals is necessary for [security](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/) reasons

**Comment by terryupton** [comment]
> @brandonkelly Internal links are still being treated as external links, in new CKEditor fields..

I see this as well on a brand new site setup with latest CKEditor plugin.
@brandonkelly

**Comment by CreateSean** [comment]
I copied what @kevinmu17 pasted above and I still don't see an option to control the target when creating a link in Craft.

Every single link whether internal or external is now opening in a new tab. Really need a solution to this..

**Comment by brandonkelly** [comment]
> I copied what @kevinmu17 pasted above and I still don't see an option to control the target when creating a link in Craft.

@CreateSean If the “Open in a new tab” decorator isn’t showing up, you must have put the decorator settings in the wrong CKEditor config, or in the wrong spot. I just copied @kevinmu17’s config verbatim to my install, to make sure there’s no typos or anything.

> Every single link whether internal or external is now opening in a new tab. Really need a solution to this.

That will only happen automatically if `link.addTargetToExternalLinks` is set to `true`.

**Comment by realjoshharrison** [comment]
Building on https://github.com/craftcms/ckeditor/issues/98#issuecomment-1569952724 from @kevinmu17, you can create a custom automatic decorator with external detection - here's my JavaScript config in the CP:

```javascript
return {
  link: {
    decorators: {
      detectExternalLinks: {
        mode: 'automatic',
        callback: url => ! url.startsWith(window.location.origin),
        attributes: {
          target: '_blank',
          rel: 'noopener noreferrer',
        }
      }
    }
  }
}
```

Obviously this only works when the front end and control panel are both running on the same origin. There's probably a better way, but it's a start!

**Comment by jeroenlammerts** [comment]
Related issue having trouble with the switch not detecting after save.

https://github.com/craftcms/ckeditor/issues/280
